-- MiZona Enterprise V8 30.83
-- SQL consolidado generado desde las migraciones 30.70 a 30.81.
-- EJECUTAR PRIMERO EN UN PROYECTO DE PRUEBA Y REVISAR CUALQUIER POLÍTICA YA EXISTENTE.

begin;

-- ===== 202607130170_app_sync_events.sql =====
-- MiZona Enterprise V8 30.70
create table if not exists public.app_sync_events (
  id bigint generated by default as identity primary key,
  client_event_id text not null unique,
  user_id uuid null references auth.users(id) on delete set null,
  local_actor_id text null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  payload jsonb not null default '{}'::jsonb,
  device_id text null,
  client_created_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists app_sync_events_user_created_idx on public.app_sync_events(user_id, created_at desc);
create index if not exists app_sync_events_entity_idx on public.app_sync_events(entity_type, entity_id, created_at desc);
alter table public.app_sync_events enable row level security;
drop policy if exists "app_sync_events_select_own" on public.app_sync_events;
create policy "app_sync_events_select_own" on public.app_sync_events for select to authenticated using (user_id = auth.uid());
drop policy if exists "app_sync_events_insert_own" on public.app_sync_events;
create policy "app_sync_events_insert_own" on public.app_sync_events for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "app_sync_events_update_own" on public.app_sync_events;
create policy "app_sync_events_update_own" on public.app_sync_events for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());


-- ===== 202607130171_commerce_core.sql =====
-- MiZona 30.71 - Núcleo normalizado para negocios, productos y pedidos
create extension if not exists pgcrypto;

create table if not exists public.mz_businesses (
  id text primary key,
  owner_user_id uuid references auth.users(id) on delete set null,
  local_owner_id text,
  name text not null,
  trade_name text,
  category text not null default 'other',
  description text,
  zone text,
  address text,
  phone text,
  hours text,
  emoji text default '🏪',
  status text not null default 'pending' check (status in ('pending','active','paused','rejected')),
  verified boolean not null default false,
  open_now boolean not null default true,
  delivery_enabled boolean not null default false,
  rating numeric(3,2) not null default 0,
  review_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_members (
  id uuid primary key default gen_random_uuid(),
  business_id text not null references public.mz_businesses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  local_user_id text,
  role text not null check (role in ('owner','manager','cashier','cook','waiter','staff')),
  status text not null default 'active' check (status in ('active','invited','suspended')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id),
  unique (business_id, local_user_id)
);

create table if not exists public.mz_products (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  name text not null,
  description text,
  category text,
  price numeric(12,2) not null default 0 check (price >= 0),
  stock numeric(12,3) not null default 0,
  minimum_stock numeric(12,3) not null default 0,
  unit text not null default 'unid.',
  image_url text,
  emoji text default '📦',
  active boolean not null default true,
  track_stock boolean not null default true,
  kitchen boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_marketplace_listings (
  id text primary key,
  seller_user_id uuid references auth.users(id) on delete set null,
  local_seller_id text,
  business_id text references public.mz_businesses(id) on delete set null,
  product_id text references public.mz_products(id) on delete set null,
  category text not null default 'other',
  title text not null,
  description text,
  price numeric(12,2) not null default 0 check (price >= 0),
  condition_label text,
  zone text,
  image_url text,
  emoji text default '📦',
  delivery boolean not null default false,
  negotiable boolean not null default false,
  verified boolean not null default false,
  status text not null default 'pending' check (status in ('pending','active','paused','sold','rejected')),
  views integer not null default 0,
  contact_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_orders (
  id text primary key,
  code text not null,
  business_id text not null references public.mz_businesses(id) on delete restrict,
  buyer_user_id uuid references auth.users(id) on delete set null,
  local_buyer_id text,
  seller_user_id uuid references auth.users(id) on delete set null,
  local_seller_id text,
  source text not null default 'marketplace' check (source in ('marketplace','business','chat','pos')),
  order_type text not null default 'pickup' check (order_type in ('pickup','delivery','table')),
  status text not null default 'pending' check (status in ('pending','confirmed','preparing','ready','delivering','delivered','cancelled','rejected')),
  customer_name text,
  customer_phone text,
  delivery_address text,
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id text not null references public.mz_orders(id) on delete cascade,
  product_id text references public.mz_products(id) on delete set null,
  listing_id text references public.mz_marketplace_listings(id) on delete set null,
  name text not null,
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0,
  line_total numeric(12,2) generated always as (quantity * unit_price) stored,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists mz_businesses_status_idx on public.mz_businesses(status, category, zone);
create index if not exists mz_products_business_idx on public.mz_products(business_id, active);
create index if not exists mz_listings_status_idx on public.mz_marketplace_listings(status, category, created_at desc);
create index if not exists mz_orders_buyer_idx on public.mz_orders(buyer_user_id, created_at desc);
create index if not exists mz_orders_business_idx on public.mz_orders(business_id, status, created_at desc);

alter table public.mz_businesses enable row level security;
alter table public.mz_business_members enable row level security;
alter table public.mz_products enable row level security;
alter table public.mz_marketplace_listings enable row level security;
alter table public.mz_orders enable row level security;
alter table public.mz_order_items enable row level security;

-- Catálogo público: solo registros activos.
drop policy if exists "mz_businesses_public_read" on public.mz_businesses;
create policy "mz_businesses_public_read" on public.mz_businesses for select using (status = 'active');
drop policy if exists "mz_products_public_read" on public.mz_products;
create policy "mz_products_public_read" on public.mz_products for select using (active = true);
drop policy if exists "mz_listings_public_read" on public.mz_marketplace_listings;
create policy "mz_listings_public_read" on public.mz_marketplace_listings for select using (status = 'active' or seller_user_id = auth.uid());

-- Propietarios y miembros administran sus negocios.
drop policy if exists "mz_businesses_owner_write" on public.mz_businesses;
create policy "mz_businesses_owner_write" on public.mz_businesses for all
using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());

drop policy if exists "mz_members_member_read" on public.mz_business_members;
create policy "mz_members_member_read" on public.mz_business_members for select
using (user_id = auth.uid() or exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid()));

drop policy if exists "mz_members_owner_write" on public.mz_business_members;
create policy "mz_members_owner_write" on public.mz_business_members for all
using (exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid()))
with check (exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid()));

drop policy if exists "mz_products_business_write" on public.mz_products;
create policy "mz_products_business_write" on public.mz_products for all
using (
  exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid())
  or exists(select 1 from public.mz_business_members m where m.business_id = mz_products.business_id and m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner','manager'))
)
with check (
  exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid())
  or exists(select 1 from public.mz_business_members m where m.business_id = mz_products.business_id and m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner','manager'))
);

drop policy if exists "mz_listings_seller_write" on public.mz_marketplace_listings;
create policy "mz_listings_seller_write" on public.mz_marketplace_listings for all
using (seller_user_id = auth.uid()) with check (seller_user_id = auth.uid());

-- Pedidos visibles para comprador o negocio vendedor.
drop policy if exists "mz_orders_participant_read" on public.mz_orders;
create policy "mz_orders_participant_read" on public.mz_orders for select using (
  buyer_user_id = auth.uid() or seller_user_id = auth.uid()
  or exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid())
  or exists(select 1 from public.mz_business_members m where m.business_id = mz_orders.business_id and m.user_id = auth.uid() and m.status = 'active')
);

drop policy if exists "mz_orders_buyer_insert" on public.mz_orders;
create policy "mz_orders_buyer_insert" on public.mz_orders for insert with check (buyer_user_id = auth.uid());

drop policy if exists "mz_orders_business_update" on public.mz_orders;
create policy "mz_orders_business_update" on public.mz_orders for update using (
  seller_user_id = auth.uid()
  or exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid())
  or exists(select 1 from public.mz_business_members m where m.business_id = mz_orders.business_id and m.user_id = auth.uid() and m.status = 'active')
);

drop policy if exists "mz_order_items_participant_read" on public.mz_order_items;
create policy "mz_order_items_participant_read" on public.mz_order_items for select using (
  exists(select 1 from public.mz_orders o where o.id = order_id and (
    o.buyer_user_id = auth.uid() or o.seller_user_id = auth.uid()
    or exists(select 1 from public.mz_businesses b where b.id = o.business_id and b.owner_user_id = auth.uid())
    or exists(select 1 from public.mz_business_members m where m.business_id = o.business_id and m.user_id = auth.uid() and m.status = 'active')
  ))
);

drop policy if exists "mz_order_items_buyer_insert" on public.mz_order_items;
create policy "mz_order_items_buyer_insert" on public.mz_order_items for insert with check (
  exists(select 1 from public.mz_orders o where o.id = order_id and o.buyer_user_id = auth.uid())
);


-- ===== 202607130172_commerce_ui_policies.sql =====
-- MiZona 30.72 - Políticas complementarias para Marketplace y Business conectados

-- El comprador puede cancelar un pedido pendiente/confirmado y confirmar recepción.
drop policy if exists "mz_orders_buyer_update" on public.mz_orders;
create policy "mz_orders_buyer_update" on public.mz_orders for update
using (buyer_user_id = auth.uid())
with check (buyer_user_id = auth.uid());

-- Permitir que propietarios lean sus propias fichas aunque estén pendientes.
drop policy if exists "mz_businesses_owner_read" on public.mz_businesses;
create policy "mz_businesses_owner_read" on public.mz_businesses for select
using (owner_user_id = auth.uid() or status = 'active');

-- Permitir leer productos inactivos solo a propietarios o administradores del negocio.
drop policy if exists "mz_products_owner_read" on public.mz_products;
create policy "mz_products_owner_read" on public.mz_products for select using (
  active = true
  or exists(select 1 from public.mz_businesses b where b.id = business_id and b.owner_user_id = auth.uid())
  or exists(select 1 from public.mz_business_members m where m.business_id = mz_products.business_id and m.user_id = auth.uid() and m.status = 'active' and m.role in ('owner','manager'))
);

-- Realtime para catálogo y pedidos.
alter publication supabase_realtime add table public.mz_businesses;
alter publication supabase_realtime add table public.mz_products;
alter publication supabase_realtime add table public.mz_marketplace_listings;
alter publication supabase_realtime add table public.mz_orders;


-- ===== 202607130173_business_operations.sql =====
-- MiZona 30.73: operaciones normalizadas de Business
create table if not exists public.mz_business_workers (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  local_user_id text null,
  role text not null check (role in ('owner','manager','cashier','cook','waiter')),
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_customers (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  name text not null,
  phone text default '',
  email text default '',
  visits integer not null default 0,
  total_spent numeric(12,2) not null default 0,
  points integer not null default 0,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_cash_sessions (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  local_user_id text null,
  opening_amount numeric(12,2) not null default 0,
  counted_amount numeric(12,2),
  expected_amount numeric(12,2),
  difference numeric(12,2),
  status text not null default 'open' check (status in ('open','closed')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_sales (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  order_id text null,
  customer_id text null references public.mz_business_customers(id) on delete set null,
  cash_session_id text null references public.mz_cash_sessions(id) on delete set null,
  cashier_user_id uuid null references auth.users(id) on delete set null,
  local_cashier_id text null,
  receipt text not null,
  payment_method text not null default 'cash',
  subtotal numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  cash_received numeric(12,2) not null default 0,
  change_amount numeric(12,2) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_sale_items (
  id bigint generated by default as identity primary key,
  sale_id text not null references public.mz_business_sales(id) on delete cascade,
  product_id text null references public.mz_products(id) on delete set null,
  name text not null,
  quantity numeric(12,3) not null default 1,
  unit_price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.mz_business_expenses (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  cash_session_id text null references public.mz_cash_sessions(id) on delete set null,
  created_by uuid null references auth.users(id) on delete set null,
  local_created_by text null,
  category text not null default 'Otros',
  description text default '',
  amount numeric(12,2) not null check (amount >= 0),
  payment_method text not null default 'cash',
  receipt_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_inventory_movements (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  product_id text not null references public.mz_products(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  local_user_id text null,
  quantity numeric(12,3) not null,
  reason text default '',
  reference_type text default 'manual',
  reference_id text null,
  created_at timestamptz not null default now()
);

create index if not exists mz_workers_business_idx on public.mz_business_workers(business_id);
create index if not exists mz_customers_business_idx on public.mz_business_customers(business_id);
create index if not exists mz_cash_business_idx on public.mz_cash_sessions(business_id, status);
create index if not exists mz_sales_business_idx on public.mz_business_sales(business_id, created_at desc);
create index if not exists mz_expenses_business_idx on public.mz_business_expenses(business_id, created_at desc);
create index if not exists mz_inventory_business_idx on public.mz_inventory_movements(business_id, created_at desc);

alter table public.mz_business_workers enable row level security;
alter table public.mz_business_customers enable row level security;
alter table public.mz_cash_sessions enable row level security;
alter table public.mz_business_sales enable row level security;
alter table public.mz_business_sale_items enable row level security;
alter table public.mz_business_expenses enable row level security;
alter table public.mz_inventory_movements enable row level security;

create or replace function public.mz_can_manage_business(target_business text)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.mz_businesses b
    where b.id=target_business and b.owner_user_id=auth.uid()
  ) or exists(
    select 1 from public.mz_business_members m
    where m.business_id=target_business and m.user_id=auth.uid() and m.status='active'
  ) or exists(
    select 1 from public.mz_business_workers w
    where w.business_id=target_business and w.user_id=auth.uid() and w.status='active'
  );
$$;

do $$ begin
  create policy "business workers read" on public.mz_business_workers for select using (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "business workers write" on public.mz_business_workers for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "business customers access" on public.mz_business_customers for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "cash sessions access" on public.mz_cash_sessions for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "business sales access" on public.mz_business_sales for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "sale items access" on public.mz_business_sale_items for all using (
    exists(select 1 from public.mz_business_sales s where s.id=sale_id and public.mz_can_manage_business(s.business_id))
  ) with check (
    exists(select 1 from public.mz_business_sales s where s.id=sale_id and public.mz_can_manage_business(s.business_id))
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "business expenses access" on public.mz_business_expenses for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "inventory movements access" on public.mz_inventory_movements for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;

alter publication supabase_realtime add table public.mz_business_workers;
alter publication supabase_realtime add table public.mz_business_customers;
alter publication supabase_realtime add table public.mz_cash_sessions;
alter publication supabase_realtime add table public.mz_business_sales;
alter publication supabase_realtime add table public.mz_business_expenses;
alter publication supabase_realtime add table public.mz_inventory_movements;


-- ===== 202607130174_ride_delivery_core.sql =====
-- MiZona 30.74: núcleo Ride y Delivery (no habilita el servicio público)
create table if not exists public.mz_ride_drivers (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  local_user_id text,
  service_types text[] not null default array['ride']::text[],
  vehicle_type text not null default 'moto',
  vehicle_brand text default '', vehicle_model text default '', vehicle_color text default '',
  plate text default '', license_number text default '',
  verification_status text not null default 'pending' check (verification_status in ('pending','verified','rejected','suspended')),
  documents_ok boolean not null default false,
  online boolean not null default false,
  rating numeric(3,2) not null default 5,
  trips_completed integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.mz_ride_requests (
  id text primary key,
  code text unique not null,
  passenger_user_id uuid references auth.users(id) on delete set null,
  local_passenger_id text,
  driver_id text references public.mz_ride_drivers(id) on delete set null,
  service_type text not null default 'auto',
  origin_label text not null, destination_label text not null,
  origin_lat numeric, origin_lng numeric, destination_lat numeric, destination_lng numeric,
  distance_km numeric not null default 0, duration_min integer not null default 0,
  fare numeric(12,2) not null default 0, payment_method text not null default 'cash',
  status text not null default 'searching' check (status in ('searching','assigned','arriving','waiting','in_progress','completed','cancelled')),
  security_code text, cancellation_reason text, rating integer, rating_comment text default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), accepted_at timestamptz, started_at timestamptz,
  completed_at timestamptz, cancelled_at timestamptz, updated_at timestamptz not null default now()
);

create table if not exists public.mz_delivery_requests (
  id text primary key,
  code text unique not null,
  customer_user_id uuid references auth.users(id) on delete set null,
  local_customer_id text,
  driver_id text references public.mz_ride_drivers(id) on delete set null,
  business_id text references public.mz_businesses(id) on delete set null,
  order_id text references public.mz_orders(id) on delete set null,
  pickup_label text not null, dropoff_label text not null,
  pickup_lat numeric, pickup_lng numeric, dropoff_lat numeric, dropoff_lng numeric,
  package_type text not null default 'package', content text default '',
  recipient_name text default '', recipient_phone text default '',
  distance_km numeric not null default 0, fare numeric(12,2) not null default 0,
  payment_method text not null default 'cash',
  status text not null default 'searching' check (status in ('searching','assigned','picked_up','in_transit','delivered','cancelled')),
  proof_note text default '', proof_url text, cancellation_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), accepted_at timestamptz, picked_up_at timestamptz,
  delivered_at timestamptz, cancelled_at timestamptz, updated_at timestamptz not null default now()
);

create table if not exists public.mz_ride_locations (
  id bigint generated always as identity primary key,
  driver_id text not null references public.mz_ride_drivers(id) on delete cascade,
  ride_id text references public.mz_ride_requests(id) on delete cascade,
  delivery_id text references public.mz_delivery_requests(id) on delete cascade,
  latitude numeric not null, longitude numeric not null, accuracy_m numeric,
  heading numeric, speed_mps numeric, recorded_at timestamptz not null default now(),
  check ((ride_id is not null) <> (delivery_id is not null))
);

create table if not exists public.mz_ride_reports (
  id text primary key,
  reporter_user_id uuid references auth.users(id) on delete set null,
  ride_id text references public.mz_ride_requests(id) on delete set null,
  delivery_id text references public.mz_delivery_requests(id) on delete set null,
  reason text not null, details text default '', emergency boolean not null default false,
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create index if not exists mz_ride_requests_passenger_idx on public.mz_ride_requests(passenger_user_id, created_at desc);
create index if not exists mz_ride_requests_driver_idx on public.mz_ride_requests(driver_id, created_at desc);
create index if not exists mz_delivery_requests_customer_idx on public.mz_delivery_requests(customer_user_id, created_at desc);
create index if not exists mz_delivery_requests_driver_idx on public.mz_delivery_requests(driver_id, created_at desc);
create index if not exists mz_ride_locations_service_idx on public.mz_ride_locations(ride_id, delivery_id, recorded_at desc);

alter table public.mz_ride_drivers enable row level security;
alter table public.mz_ride_requests enable row level security;
alter table public.mz_delivery_requests enable row level security;
alter table public.mz_ride_locations enable row level security;
alter table public.mz_ride_reports enable row level security;

create policy "ride drivers read authenticated" on public.mz_ride_drivers for select to authenticated using (true);
create policy "ride driver manages own profile" on public.mz_ride_drivers for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "ride passenger reads own" on public.mz_ride_requests for select to authenticated using (passenger_user_id = auth.uid() or driver_id in (select id from public.mz_ride_drivers where user_id=auth.uid()));
create policy "ride passenger creates own" on public.mz_ride_requests for insert to authenticated with check (passenger_user_id = auth.uid());
create policy "ride participants update" on public.mz_ride_requests for update to authenticated using (passenger_user_id = auth.uid() or driver_id in (select id from public.mz_ride_drivers where user_id=auth.uid()));
create policy "delivery participants read" on public.mz_delivery_requests for select to authenticated using (customer_user_id = auth.uid() or driver_id in (select id from public.mz_ride_drivers where user_id=auth.uid()));
create policy "delivery customer creates" on public.mz_delivery_requests for insert to authenticated with check (customer_user_id = auth.uid());
create policy "delivery participants update" on public.mz_delivery_requests for update to authenticated using (customer_user_id = auth.uid() or driver_id in (select id from public.mz_ride_drivers where user_id=auth.uid()));
create policy "ride participants read locations" on public.mz_ride_locations for select to authenticated using (
  driver_id in (select id from public.mz_ride_drivers where user_id=auth.uid()) or
  ride_id in (select id from public.mz_ride_requests where passenger_user_id=auth.uid()) or
  delivery_id in (select id from public.mz_delivery_requests where customer_user_id=auth.uid())
);
create policy "driver writes locations" on public.mz_ride_locations for insert to authenticated with check (driver_id in (select id from public.mz_ride_drivers where user_id=auth.uid()));
create policy "reporter manages reports" on public.mz_ride_reports for all to authenticated using (reporter_user_id=auth.uid()) with check (reporter_user_id=auth.uid());

alter publication supabase_realtime add table public.mz_ride_requests;
alter publication supabase_realtime add table public.mz_delivery_requests;
alter publication supabase_realtime add table public.mz_ride_locations;


-- ===== 202607130175_committees_transparency.sql =====
create table if not exists public.mz_committees (
 id uuid primary key default gen_random_uuid(), zone_id text not null, name text not null,
 description text, status text not null default 'active', created_by uuid not null references auth.users(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.mz_committee_members (
 id uuid primary key default gen_random_uuid(), committee_id uuid not null references public.mz_committees(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member', active boolean not null default true,
 joined_at timestamptz not null default now(), unique(committee_id,user_id)
);
create table if not exists public.mz_committee_movements (
 id uuid primary key default gen_random_uuid(), committee_id uuid not null references public.mz_committees(id) on delete cascade,
 movement_type text not null check (movement_type in ('income','expense')), category text not null, concept text not null,
 detail text, amount numeric(14,2) not null check(amount>=0), movement_date date not null default current_date,
 evidence jsonb not null default '[]'::jsonb, status text not null default 'registered', created_by uuid not null references auth.users(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.mz_committee_events (
 id uuid primary key default gen_random_uuid(), committee_id uuid not null references public.mz_committees(id) on delete cascade,
 title text not null, description text, starts_at timestamptz not null, ends_at timestamptz,
 location text, publish_home boolean not null default false, status text not null default 'scheduled', created_by uuid not null references auth.users(id),
 created_at timestamptz not null default now()
);
alter table public.mz_committees enable row level security;
alter table public.mz_committee_members enable row level security;
alter table public.mz_committee_movements enable row level security;
alter table public.mz_committee_events enable row level security;
create or replace function public.mz_is_committee_member(cid uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.mz_committee_members m where m.committee_id=cid and m.user_id=auth.uid() and m.active);
$$;
create policy "committee read members" on public.mz_committees for select using (created_by=auth.uid() or public.mz_is_committee_member(id));
create policy "committee create" on public.mz_committees for insert with check (created_by=auth.uid());
create policy "committee owner update" on public.mz_committees for update using (created_by=auth.uid());
create policy "committee members read" on public.mz_committee_members for select using (user_id=auth.uid() or public.mz_is_committee_member(committee_id));
create policy "committee finance read" on public.mz_committee_movements for select using (public.mz_is_committee_member(committee_id));
create policy "committee finance write" on public.mz_committee_movements for all using (public.mz_is_committee_member(committee_id)) with check (public.mz_is_committee_member(committee_id) and created_by=auth.uid());
create policy "committee events read" on public.mz_committee_events for select using (publish_home or public.mz_is_committee_member(committee_id));
create policy "committee events write" on public.mz_committee_events for all using (public.mz_is_committee_member(committee_id)) with check (public.mz_is_committee_member(committee_id) and created_by=auth.uid());


-- ===== 202607130176_campus_learning.sql =====
create table if not exists public.mz_courses(id uuid primary key default gen_random_uuid(), title text not null, description text, level text, published boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.mz_course_lessons(id uuid primary key default gen_random_uuid(), course_id uuid not null references public.mz_courses(id) on delete cascade, title text not null, content jsonb not null default '{}'::jsonb, position int not null default 0, published boolean not null default false);
create table if not exists public.mz_course_enrollments(id uuid primary key default gen_random_uuid(), course_id uuid not null references public.mz_courses(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, enrolled_at timestamptz not null default now(), unique(course_id,user_id));
create table if not exists public.mz_lesson_progress(id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.mz_course_lessons(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, progress int not null default 0 check(progress between 0 and 100), completed_at timestamptz, updated_at timestamptz not null default now(), unique(lesson_id,user_id));
create table if not exists public.mz_assessments(id uuid primary key default gen_random_uuid(), course_id uuid not null references public.mz_courses(id) on delete cascade, title text not null, questions jsonb not null default '[]'::jsonb, passing_score int not null default 70);
create table if not exists public.mz_assessment_attempts(id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.mz_assessments(id) on delete cascade, user_id uuid not null references auth.users(id), answers jsonb not null default '{}'::jsonb, score numeric(5,2), passed boolean, submitted_at timestamptz not null default now());
alter table public.mz_courses enable row level security; alter table public.mz_course_lessons enable row level security; alter table public.mz_course_enrollments enable row level security; alter table public.mz_lesson_progress enable row level security; alter table public.mz_assessments enable row level security; alter table public.mz_assessment_attempts enable row level security;
create policy "courses public read" on public.mz_courses for select using (published or created_by=auth.uid());
create policy "lessons public read" on public.mz_course_lessons for select using (published);
create policy "own enrollment" on public.mz_course_enrollments for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own progress" on public.mz_lesson_progress for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "assessment read" on public.mz_assessments for select using(true);
create policy "own attempts" on public.mz_assessment_attempts for all using(user_id=auth.uid()) with check(user_id=auth.uid());


-- ===== 202607130177_benefits.sql =====
create table if not exists public.mz_benefit_partners(id uuid primary key default gen_random_uuid(), name text not null, description text, logo_url text, contact jsonb not null default '{}'::jsonb, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.mz_benefits(id uuid primary key default gen_random_uuid(), partner_id uuid references public.mz_benefit_partners(id) on delete cascade, title text not null, description text, discount_text text, terms text, starts_at timestamptz, ends_at timestamptz, redemption_limit int, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.mz_benefit_redemptions(id uuid primary key default gen_random_uuid(), benefit_id uuid not null references public.mz_benefits(id) on delete cascade, user_id uuid not null references auth.users(id), code text not null, status text not null default 'issued', issued_at timestamptz not null default now(), redeemed_at timestamptz, unique(benefit_id,user_id));
alter table public.mz_benefit_partners enable row level security; alter table public.mz_benefits enable row level security; alter table public.mz_benefit_redemptions enable row level security;
create policy "partners public" on public.mz_benefit_partners for select using(active);
create policy "benefits public" on public.mz_benefits for select using(active and (ends_at is null or ends_at>now()));
create policy "own redemptions" on public.mz_benefit_redemptions for all using(user_id=auth.uid()) with check(user_id=auth.uid());


-- ===== 202607130178_users_roles.sql =====
create table if not exists public.mz_user_profiles(user_id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, phrase text, phone text, zone_id text, account_status text not null default 'active', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.mz_roles(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text, is_system boolean not null default false);
create table if not exists public.mz_role_permissions(role_id uuid not null references public.mz_roles(id) on delete cascade, module text not null, can_view boolean not null default false, can_create boolean not null default false, can_edit boolean not null default false, can_delete boolean not null default false, primary key(role_id,module));
create table if not exists public.mz_user_roles(user_id uuid not null references auth.users(id) on delete cascade, role_id uuid not null references public.mz_roles(id) on delete cascade, scope_type text not null default 'global', scope_id text not null default '*', assigned_at timestamptz not null default now(), assigned_by uuid references auth.users(id), primary key(user_id,role_id,scope_type,scope_id));
alter table public.mz_user_profiles enable row level security; alter table public.mz_roles enable row level security; alter table public.mz_role_permissions enable row level security; alter table public.mz_user_roles enable row level security;
create policy "profile public read" on public.mz_user_profiles for select using(true);
create policy "own profile write" on public.mz_user_profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "roles authenticated read" on public.mz_roles for select to authenticated using(true);
create policy "permissions authenticated read" on public.mz_role_permissions for select to authenticated using(true);
create policy "own roles read" on public.mz_user_roles for select using(user_id=auth.uid());
insert into public.mz_roles(code,name,is_system) values ('admin','Administrador',true),('resident','Residente',true),('business_owner','Propietario de negocio',true),('committee_member','Miembro de comité',true) on conflict(code) do nothing;


-- ===== 202607130179_notifications.sql =====
create table if not exists public.mz_notification_devices(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, platform text not null, token text not null unique, device_name text, active boolean not null default true, updated_at timestamptz not null default now());
create table if not exists public.mz_notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, category text not null default 'general', title text not null, body text not null, data jsonb not null default '{}'::jsonb, read_at timestamptz, created_at timestamptz not null default now());
create index if not exists mz_notifications_user_created_idx on public.mz_notifications(user_id,created_at desc);
alter table public.mz_notification_devices enable row level security; alter table public.mz_notifications enable row level security;
create policy "own device tokens" on public.mz_notification_devices for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own notifications" on public.mz_notifications for select using(user_id=auth.uid());
create policy "mark own notification" on public.mz_notifications for update using(user_id=auth.uid());


-- ===== 202607130180_storage_files.sql =====
create table if not exists public.mz_files(id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, bucket text not null default 'mizona-files', object_path text not null unique, file_name text not null, mime_type text, size_bytes bigint, module text not null default 'general', entity_id text, visibility text not null default 'private', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.mz_files enable row level security;
create policy "own private file metadata" on public.mz_files for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('mizona-files','mizona-files',false,26214400,array['image/jpeg','image/png','image/webp','video/mp4','audio/webm','audio/mpeg','application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']) on conflict(id) do update set file_size_limit=excluded.file_size_limit;
create policy "upload own mizona files" on storage.objects for insert to authenticated with check(bucket_id='mizona-files' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "read own mizona files" on storage.objects for select to authenticated using(bucket_id='mizona-files' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "delete own mizona files" on storage.objects for delete to authenticated using(bucket_id='mizona-files' and (storage.foldername(name))[1]=auth.uid()::text);


-- ===== 202607130181_privacy_security.sql =====
create table if not exists public.mz_blocks(blocker_id uuid not null references auth.users(id) on delete cascade, blocked_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(blocker_id,blocked_id), check(blocker_id<>blocked_id));
create table if not exists public.mz_reports(id uuid primary key default gen_random_uuid(), reporter_id uuid not null references auth.users(id), target_type text not null, target_id text not null, reason text not null, detail text, status text not null default 'open', created_at timestamptz not null default now());
create table if not exists public.mz_account_deletion_requests(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), reason text, status text not null default 'requested', requested_at timestamptz not null default now(), processed_at timestamptz);
create table if not exists public.mz_audit_log(id bigint generated always as identity primary key, actor_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.mz_blocks enable row level security; alter table public.mz_reports enable row level security; alter table public.mz_account_deletion_requests enable row level security; alter table public.mz_audit_log enable row level security;
create policy "own blocks" on public.mz_blocks for all using(blocker_id=auth.uid()) with check(blocker_id=auth.uid());
create policy "own reports create" on public.mz_reports for insert with check(reporter_id=auth.uid());
create policy "own reports read" on public.mz_reports for select using(reporter_id=auth.uid());
create policy "own deletion request" on public.mz_account_deletion_requests for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own audit read" on public.mz_audit_log for select using(actor_id=auth.uid());


commit;
