const modules = [
  {id:'panel', icon:'🏠', name:'Mi Panel', status:'active'},
  {id:'comunidad', icon:'👥', name:'Mi Comunidad', status:'active'},
  {id:'chat', icon:'💬', name:'MiZona Chat', status:'beta'},
  {id:'beneficios', icon:'🎁', name:'Beneficios', status:'beta'},
  {id:'negocios', icon:'🏪', name:'Negocios', status:'beta'},
  {id:'servicios', icon:'🛠️', name:'Servicios', status:'off'},
  {id:'marketplace', icon:'🛒', name:'Marketplace', status:'off'},
  {id:'business', icon:'💼', name:'MiZona Business', status:'off'},
  {id:'campus', icon:'🎓', name:'CampusHugo', status:'off'},
  {id:'ride', icon:'🚕', name:'MiZona Ride', status:'off'},
  {id:'admin', icon:'⚙️', name:'Centro de Control', status:'active'},
  {id:'design', icon:'🎨', name:'Design System', status:'active'}
];
const statusLabel = {active:'Activo', beta:'Pruebas', off:'Próximamente', maint:'Mantenimiento'};
const statusClass = {active:'active', beta:'beta', off:'off', maint:'maint'};
let current = 'panel';
function nav(){
  const el=document.getElementById('mainNav');
  el.innerHTML=modules.map(m=>`<button class="${current===m.id?'active':''}" onclick="go('${m.id}')"><span>${m.icon} ${m.name}</span>${m.status!=='active'?`<small>${statusLabel[m.status]}</small>`:''}</button>`).join('');
}
function tag(s){return `<span class="tag ${statusClass[s]}">● ${statusLabel[s]}</span>`}
function go(id){current=id; nav(); render(); document.getElementById('sidebar').classList.remove('open')}
function render(){document.getElementById('view').className='view'; document.getElementById('view').innerHTML = views[current] ? views[current]() : coming(current)}
const views={
panel:()=>`<div class="hero"><div class="hero-card"><h2>¿Qué necesitas hoy, José?</h2><p>MiZona empieza resolviendo problemas reales: colegio, comunidad, chat seguro, oportunidades y beneficios de tu zona.</p><div class="hero-actions"><button class="btn white">🔎 Buscar solución</button><button class="btn orange">🏫 Ver mi colegio</button><button class="btn ghost">💬 Abrir MiZona Chat</button></div></div><div class="stat-panel"><h3>Radar de hoy</h3><div class="stat-row"><span>🏫 Comunicados escolares</span><b>3</b></div><div class="stat-row"><span>💬 Chats activos</span><b>12</b></div><div class="stat-row"><span>🎁 Beneficios en pruebas</span><b>8</b></div><div class="stat-row"><span>🚧 Módulos futuros</span><b>6</b></div></div></div><div class="section-title"><div><h2>Etapas visibles desde ahora</h2><p>Todo existe en estructura, pero el administrador decide qué se activa.</p></div></div><div class="grid cols-4">${modules.filter(m=>m.id!=='admin'&&m.id!=='design').map(m=>`<div class="card module-card"><div class="module-icon">${m.icon}</div><div><h3>${m.name}</h3>${tag(m.status)}<p>${desc(m.id)}</p></div></div>`).join('')}</div><div class="section-title"><div><h2>Actividad útil</h2><p>No será un muro de Facebook. Será actividad que resuelve necesidades.</p></div></div><div class="grid cols-2"><div class="card"><h3>📍 Cambios importantes</h3><div class="timeline"><div class="activity">🏫 <div><b>Colegio San Martín</b><span>Publicó comunicado para padres.</span></div></div><div class="activity">💬 <div><b>Aula Chat</b><span>Grupo “Trabajo de Ciencia” activo por 7 días.</span></div></div><div class="activity">🎁 <div><b>Beneficio local</b><span>Próximamente: cupones de ahorro por zona.</span></div></div></div></div><div class="card"><h3>🧭 Filosofía V8</h3><p>Primero resolvemos problemas actuales de colegios, comités y comunidades. Luego activamos beneficios, negocios, Business, Ride y CampusHugo desde el administrador.</p><div class="notice">Regla: los módulos futuros se muestran como “Próximamente” o “Mantenimiento”, nunca como pantallas rotas.</div></div></div>`,
comunidad:()=>`<div class="section-title"><div><h2>👥 Mi Comunidad</h2><p>Primer motor de crecimiento: colegios, comités, urbanizaciones, clubes, empresas e iglesias.</p></div>${tag('active')}</div><div class="grid cols-3"><div class="card"><h3>🏫 Colegio</h3><p>Comunicados, aula chat, tareas, archivos temporales, eventos, encuestas y grupos de trabajo.</p><button class="btn">Abrir ejemplo</button></div><div class="card"><h3>🏘️ Comité / Urbanización</h3><p>Avisos, acuerdos, eventos, documentos, cuotas futuras y mensajes oficiales.</p><button class="btn ghost">Próximamente</button></div><div class="card"><h3>⚽ Club / Asociación</h3><p>Actividades, inscripciones, calendario, galería y comunicados.</p><button class="btn ghost">Próximamente</button></div></div><div class="section-title"><div><h2>Panel colegio</h2><p>Apariencia base para el primer módulo operativo.</p></div></div><div class="grid cols-4"><div class="card"><h3>📢 Comunicados</h3><p>Publicación oficial con opción de compartir por WhatsApp, Facebook, Instagram y QR.</p></div><div class="card"><h3>💬 Aula Chat</h3><p>Chats y grupos solo del mismo colegio. Mensajes y archivos expiran en 7 días.</p></div><div class="card"><h3>📁 Tareas y archivos</h3><p>Adjuntos pequeños en chat. Archivos pesados por MiZona Transfer.</p></div><div class="card"><h3>📅 Eventos</h3><p>Actuaciones, reuniones, actividades y recordatorios.</p></div></div>`,
chat:()=>`<div class="section-title"><div><h2>💬 MiZona Chat</h2><p>Identidad digital con usuario único. No depende del número de celular.</p></div>${tag('beta')}</div><div class="grid cols-3"><div class="card"><h3>🔐 Identidad</h3><p>Usuario único, foto de perfil, reglas contra nombres vulgares, correo único y control antifraude.</p></div><div class="card"><h3>🔎 Búsqueda segura</h3><p>Solo por nombre de usuario exacto. Sin búsqueda pública de escolares.</p></div><div class="card"><h3>🏫 Aula Chat</h3><p>Sin chat entre colegios al inicio. Grupos por salón y trabajos. Archivos 7 días.</p></div></div><div class="grid cols-2"><div class="card"><h3>Reglas iniciales</h3><table class="table"><tr><th>Caso</th><th>Regla</th></tr><tr><td>Adulto ↔ Adulto</td><td>Solicitud por usuario exacto</td></tr><tr><td>Alumno ↔ Alumno</td><td>Solo mismo colegio/salón</td></tr><tr><td>Entre colegios</td><td>Desactivado</td></tr><tr><td>Archivos</td><td>Vencen en 7 días</td></tr><tr><td>Videollamada</td><td>Próximamente</td></tr></table></div><div class="card"><h3>MiZona Transfer</h3><p>Subida temporal para archivos pesados de tareas o trabajos.</p><div class="notice">Los chats quedan visibles solo 7 días. Luego se eliminan mensajes y adjuntos para cuidar el almacenamiento gratuito.</div></div></div>`,
beneficios:()=>`<div class="section-title"><div><h2>🎁 Beneficios</h2><p>Motor de frecuencia futura: ahorro, cupones, oportunidades y promociones.</p></div>${tag('beta')}</div><div class="grid cols-3"><div class="card"><h3>🔥 Ofertas</h3><p>Se activará cuando existan comunidades y usuarios suficientes.</p></div><div class="card"><h3>🏷️ Cupones</h3><p>Medición por QR o código para demostrar resultados.</p></div><div class="card"><h3>📊 Resultados</h3><p>Vistas, guardados, canjes, clientes confirmados.</p></div></div>`,
negocios:()=>`<div class="section-title"><div><h2>🏪 Negocios</h2><p>Los negocios llegan después de crear usuarios mediante comunidades.</p></div>${tag('beta')}</div><div class="grid cols-3"><div class="card"><h3>Perfil gratuito</h3><p>Nombre, rubro, ubicación, horario, contacto y reseñas.</p></div><div class="card"><h3>Verificado MiZona</h3><p>Logo, promociones, chat, cupones y estadísticas.</p></div><div class="card"><h3>Activar Business</h3><p>Cuando el negocio quiera gestionar ventas, caja, reportes e inventario.</p></div></div>`,
admin:()=>`<div class="section-title"><div><h2>⚙️ Centro de Control MiZona</h2><p>El administrador controla la evolución completa de la plataforma.</p></div>${tag('active')}</div><div class="admin-layout"><div class="card"><h3>Módulos del sistema</h3><table class="table"><tr><th>Módulo</th><th>Estado</th><th>Visible</th><th>Acción</th></tr>${modules.filter(m=>m.id!=='admin').map(m=>`<tr><td>${m.icon} ${m.name}</td><td>${tag(m.status)}</td><td>${m.status==='off'?'No':'Sí'}</td><td><button class="switch">Configurar</button></td></tr>`).join('')}</table></div><div class="card"><h3>Controles globales</h3><p>Desde aquí se habilita, desactiva, pone en mantenimiento o cambia el orden de cada módulo.</p><div class="timeline"><div class="activity">🟢 <div><b>Activo</b><span>Visible y operativo.</span></div></div><div class="activity">🟡 <div><b>Pruebas</b><span>Visible para usuarios definidos.</span></div></div><div class="activity">🔴 <div><b>Mantenimiento</b><span>Mensaje de pausa temporal.</span></div></div><div class="activity">⚪ <div><b>Desactivado</b><span>Se muestra como Próximamente o se oculta.</span></div></div></div></div></div>`,
design:()=>`<div class="section-title"><div><h2>🎨 Design System V8</h2><p>Base visual que usaremos para todas las pantallas futuras.</p></div>${tag('active')}</div><div class="grid cols-3"><div class="card"><h3>Colores</h3><p>Azul confianza, naranja oportunidad, verde acción, fondos claros y modo oscuro futuro.</p><button class="btn">Botón principal</button> <button class="btn ghost">Secundario</button></div><div class="card"><h3>Componentes</h3><p>Tarjetas, tablas, avisos, chats, formularios, fichas de comunidad y módulos próximamente.</p></div><div class="card"><h3>Responsive</h3><p>Celular primero, luego tablet, PC y TV. Máximo 7 opciones principales por pantalla.</p></div></div><div class="section-title"><div><h2>Vista móvil de referencia</h2></div></div><div class="mock-phone"><div class="phone-top"></div><div class="phone-content"><h3>MiZona</h3><div class="phone-card">🔎 ¿Qué necesitas hoy?</div><div class="phone-card">🏫 Colegio San Martín · 2 avisos</div><div class="phone-card">💬 Aula Chat · Grupo Ciencia</div><div class="phone-card">🎁 Beneficios · Próximamente</div></div></div>`
};
function desc(id){return ({panel:'Pantalla principal personalizada según zona, rol y necesidades.',comunidad:'Colegios y comités serán el primer motor de usuarios.',chat:'Usuario único, invitaciones, aula chat y archivos temporales.',beneficios:'Ofertas y cupones cuando exista base de usuarios.',negocios:'Perfiles y promociones, luego Business.',servicios:'Profesionales y soluciones locales.',marketplace:'Compra, venta y oportunidades futuras.',business:'Gestión para negocios cuando el ecosistema crezca.',campus:'Cursos y aprendizaje en fase posterior.',ride:'Movilidad, delivery y envíos más adelante.'}[id]||'Módulo preparado para activarse desde administración.')}
function coming(id){const m=modules.find(x=>x.id===id); return `<div class="section-title"><div><h2>${m.icon} ${m.name}</h2><p>Este módulo existe en estructura, pero se activará cuando llegue su fase.</p></div>${tag(m.status)}</div><div class="card"><h3>🚧 Próximamente</h3><p>El administrador podrá activarlo, ocultarlo o ponerlo en mantenimiento sin cambiar el código.</p></div>`}
document.getElementById('toggleSidebar').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){alert('Prototipo: aquí MiZona buscará soluciones por necesidad, zona y rol.')}});
nav(); render();
