import { useEffect, useMemo, useState } from 'react';
import Card from '../components/Card';
import StatusPill from '../components/StatusPill';
import Tabs from '../components/Tabs';
import { useApp } from '../context/AppContext';
import { supabase } from '../lib/supabase';
import { cleanupExpiredLocalData, exportLocalBackup, getLocalStats, listLocalAuditLogs, listLocalReports, listLocalSyncQueue, resetLocalData, reviewLocalReport, subscribeLocalData } from '../lib/localStore';
import { getLocalBenefitsSnapshot, reviewLocalOpportunity, reviewLocalOpportunityReport, subscribeLocalBenefits } from '../lib/localBenefits';
import { getLocalCommerceSnapshot, reviewLocalBusiness, reviewLocalBusinessClaim, reviewLocalBusinessReport, reviewLocalListing, reviewLocalListingReport, subscribeLocalCommerce } from '../lib/localCommerce';

const campaigns=[
 {id:1,title:'Combo familiar de pollo',owner:'Pollería El Buen Sabor',type:'Oferta',status:'active',views:1260,actions:184},
 {id:2,title:'Campaña médica gratuita',owner:'Centro de Salud Pachacútec',type:'Campaña',status:'active',views:840,actions:92},
 {id:3,title:'Auxiliar de caja',owner:'Mercado Central',type:'Empleo',status:'beta',views:610,actions:47},
 {id:4,title:'2x1 entradas infantiles',owner:'Cine Plaza Ventanilla',type:'Cupón',status:'maintenance',views:430,actions:68}
];

const campusCourses=[
 {title:'Excel desde cero',teacher:'Daniela Ramos',students:1284,status:'active'},
 {title:'Power BI para principiantes',teacher:'Marco Salazar',students:716,status:'beta'},
 {title:'Matemática práctica secundaria',teacher:'Luis Medina',students:493,status:'active'},
 {title:'Vende más en tu zona',teacher:'Carla Torres',students:362,status:'maintenance'}
];

export default function Admin(){
 const { moduleConfig, updateModuleStatus, resetModules, backendConnected, profile, dataMode, online } = useApp();
 const [tab,setTab]=useState('modules');
 const [campaignState,setCampaignState]=useState(campaigns);
 const [chatReports,setChatReports]=useState([]);
 const [chatReportMessage,setChatReportMessage]=useState('');
 const [localStats,setLocalStats]=useState(getLocalStats);
 const [auditLogs,setAuditLogs]=useState(listLocalAuditLogs);
 const [syncQueue,setSyncQueue]=useState(listLocalSyncQueue);
 const [maintenanceMessage,setMaintenanceMessage]=useState('');
 const [benefitSnapshot,setBenefitSnapshot]=useState(getLocalBenefitsSnapshot);
 const [commerceSnapshot,setCommerceSnapshot]=useState(getLocalCommerceSnapshot);
 const counts=useMemo(()=>moduleConfig.reduce((a,m)=>({...a,[m.status]:(a[m.status]||0)+1}),{}),[moduleConfig]);
 const cycle=s=>s==='active'?'beta':s==='beta'?'maintenance':s==='maintenance'?'soon':'active';
 const toggleCampaign=id=>setCampaignState(arr=>arr.map(x=>x.id===id?{...x,status:x.status==='active'?'maintenance':'active'}:x));
 const moderateOpportunity=(id,status,verified=null)=>{try{reviewLocalOpportunity(id,status,verified);setBenefitSnapshot(getLocalBenefitsSnapshot());}catch(error){setMaintenanceMessage(error.message);}};
 const moderateBenefitReport=(id,status)=>{try{reviewLocalOpportunityReport(id,status);setBenefitSnapshot(getLocalBenefitsSnapshot());}catch(error){setMaintenanceMessage(error.message);}};
 const refreshCommerce=()=>setCommerceSnapshot(getLocalCommerceSnapshot());
 const moderateBusiness=(id,status,verified=null)=>{try{reviewLocalBusiness(id,status,verified);refreshCommerce();}catch(error){setMaintenanceMessage(error.message);}};
 const moderateClaim=(id,status)=>{try{reviewLocalBusinessClaim(id,status);refreshCommerce();}catch(error){setMaintenanceMessage(error.message);}};
 const moderateBusinessReport=(id,status)=>{try{reviewLocalBusinessReport(id,status);refreshCommerce();}catch(error){setMaintenanceMessage(error.message);}};
 const moderateListing=(id,status,verified=null)=>{try{reviewLocalListing(id,status,verified);refreshCommerce();}catch(error){setMaintenanceMessage(error.message);}};
 const moderateListingReport=(id,status)=>{try{reviewLocalListingReport(id,status);refreshCommerce();}catch(error){setMaintenanceMessage(error.message);}};
 useEffect(()=>{
  const refreshLocal=()=>{setLocalStats(getLocalStats());setAuditLogs(listLocalAuditLogs());setSyncQueue(listLocalSyncQueue());if(!backendConnected)setChatReports(listLocalReports());};
  refreshLocal();
  const unsubscribe=subscribeLocalData(refreshLocal);
  if(tab==='chatReports'&&backendConnected&&supabase){
   supabase.from('mz_chat_reports').select('id,reporter_id,conversation_id,message_id,reported_user_id,reason,details,status,created_at').order('created_at',{ascending:false}).limit(50).then(({data,error})=>{if(error)setChatReportMessage(error.message);else setChatReports(data||[]);});
  }
  return unsubscribe;
 },[tab,backendConnected]);
 useEffect(()=>subscribeLocalBenefits(setBenefitSnapshot),[]);
 useEffect(()=>subscribeLocalCommerce(setCommerceSnapshot),[]);
 const reviewChatReport=async(id,status)=>{
  if(!backendConnected){
   try{reviewLocalReport(id,status,profile.id);setChatReports(listLocalReports());setChatReportMessage('Reporte actualizado en este dispositivo.');}catch(error){setChatReportMessage(error.message);}return;
  }
  if(!supabase)return;
  const {error}=await supabase.from('mz_chat_reports').update({status,reviewed_at:new Date().toISOString(),reviewed_by:profile.id||null}).eq('id',id);
  if(error)setChatReportMessage(error.message);else setChatReports(rows=>rows.map(row=>row.id===id?{...row,status}:row));
 };
 const runCleanup=async()=>{const result=await cleanupExpiredLocalData();setMaintenanceMessage(`Limpieza terminada: ${result.removedMessages} mensajes y ${result.removedFiles} archivos vencidos eliminados.`);setLocalStats(getLocalStats());};
 const resetLocal=()=>{if(!window.confirm('¿Restablecer todos los datos locales de demostración de este dispositivo?'))return;resetLocalData();setMaintenanceMessage('Datos locales restablecidos.');};
 const tabs=[{id:'modules',label:'Módulos',icon:'🧩'},{id:'benefits',label:'Beneficios',icon:'🎁'},{id:'places',label:'Negocios',icon:'🏪'},{id:'market',label:'Marketplace',icon:'🛒'},{id:'campus',label:'CampusHugo',icon:'🎓'},{id:'businessSuite',label:'MiZona Business',icon:'🧾'},{id:'rideAdmin',label:'MiZona Ride',icon:'🚗'},{id:'aiAdmin',label:'IA MiZona',icon:'✨'},{id:'chatReports',label:'Moderación local',icon:'💬'},{id:'contingency',label:'Contingencia',icon:'📦'},{id:'audit',label:'Auditoría',icon:'🧾'},{id:'security',label:'Seguridad',icon:'🛡️'},{id:'storage',label:'Storage',icon:'🧹'}];
 return <div className="page"><h1>Centro de Control Enterprise</h1><p className="muted">Controla módulos, permisos, comunidades, chat, beneficios, storage y evolución de MiZona.</p><div className={`connectionBadge ${backendConnected ? 'connected' : ''}`}>{backendConnected ? `Backend conectado · ${profile.role}` : `Modo local operativo · ${profile.role}`}</div><div className="stats"><span>🟢 Activos: {counts.active||0}</span><span>🟡 Beta: {counts.beta||0}</span><span>🔴 Mant.: {counts.maintenance||0}</span><span>⚪ Próx.: {counts.soon||0}</span></div><Tabs tabs={tabs} active={tab} setActive={setTab}/>
 {tab==='modules'&&<div className="grid2"><Card title="Control de módulos" icon="🧩"><div className="adminTable">{moduleConfig.map((m)=><div key={m.id}><b>{m.label}</b><span>{m.audience}</span><StatusPill status={m.status}/><button onClick={()=>updateModuleStatus(m.id,cycle(m.status))}>Cambiar</button></div>)}</div><button className="ghost" onClick={resetModules}>Restablecer estados</button></Card><Card title="Políticas activas" icon="🛡"><ul className="list"><li>No chat entre colegios.</li><li>Aula Chat solo con alumnos validados.</li><li>Chats y archivos vencen en 7 días.</li><li>Usuario único y nombres no vulgares.</li><li>Adultos no buscan escolares.</li><li>Beneficios requieren fecha de vigencia y responsable.</li></ul></Card></div>}
 {tab==='benefits'&&<><div className="adminKpis"><span><b>{benefitSnapshot.opportunities.reduce((sum,item)=>sum+Number(item.views||0),0)}</b> vistas</span><span><b>{benefitSnapshot.opportunities.reduce((sum,item)=>sum+Number(item.action_count||0),0)}</b> acciones</span><span><b>{benefitSnapshot.pendingCount}</b> pendientes</span><span><b>{benefitSnapshot.reportPendingCount}</b> reportes</span></div>{maintenanceMessage&&<p className="accountMessage">{maintenanceMessage}</p>}<div className="grid2 benefitsAdminV16"><Card title="Moderación de oportunidades locales" icon="🎁"><p className="muted">Publicaciones compartidas entre perfiles de este navegador.</p><div className="benefitAdminList">{benefitSnapshot.opportunities.slice().sort((a,b)=>(a.status==='pending'?-1:1)-(b.status==='pending'?-1:1)).map(item=><article key={item.id}><div><b>{item.title}</b><span>{item.owner_name} · {item.type} · {item.views||0} vistas · {item.action_count||0} acciones</span></div><StatusPill status={item.status==='active'?'active':item.status==='pending'?'beta':'maintenance'}/><div className="benefitAdminActions">{item.status!=='active'&&<button onClick={()=>moderateOpportunity(item.id,'active',true)}>Aprobar</button>}{item.status==='active'&&<button onClick={()=>moderateOpportunity(item.id,'paused',item.verified)}>Pausar</button>}{!item.verified&&<button onClick={()=>moderateOpportunity(item.id,item.status,true)}>Verificar</button>}<button className="dangerButton" onClick={()=>moderateOpportunity(item.id,'rejected',false)}>Rechazar</button></div></article>)}</div></Card><Card title="Reportes de oportunidades" icon="🚩"><div className="benefitAdminList">{benefitSnapshot.reports.length?benefitSnapshot.reports.map(report=>{const item=benefitSnapshot.opportunities.find(row=>row.id===report.opportunity_id);return <article key={report.id}><div><b>{report.reason}</b><span>{item?.title||'Publicación'} · {report.details||'Sin detalle'}</span></div><StatusPill status={report.status==='resolved'||report.status==='dismissed'?'active':report.status==='reviewing'?'maintenance':'beta'}/><div className="benefitAdminActions">{report.status==='pending'&&<button onClick={()=>moderateBenefitReport(report.id,'reviewing')}>Revisar</button>}<button onClick={()=>moderateBenefitReport(report.id,'resolved')}>Resolver</button><button onClick={()=>moderateBenefitReport(report.id,'dismissed')}>Descartar</button></div></article>}):<p className="muted">No hay reportes locales.</p>}</div></Card></div></>}

 {tab==='places'&&<><div className="adminKpis"><span><b>{commerceSnapshot.businesses.length}</b> fichas visibles</span><span><b>{commerceSnapshot.businesses.filter(x=>x.affiliated).length}</b> afiliados</span><span><b>{commerceSnapshot.pendingClaimCount}</b> reclamos pendientes</span><span><b>{commerceSnapshot.pendingBusinessReportCount}</b> reportes</span></div>{maintenanceMessage&&<p className="accountMessage">{maintenanceMessage}</p>}<div className="grid2"><Card title="Moderación de negocios locales" icon="🏪"><div className="benefitAdminList">{commerceSnapshot.businesses.slice().sort((a,b)=>(a.status==='pending'?-1:1)-(b.status==='pending'?-1:1)).map(item=><article key={item.id}><div><b>{item.emoji} {item.name}</b><span>{item.zone} · {item.owner?.username?'@'+item.owner.username:'sin propietario'} · {item.views||0} vistas</span></div><StatusPill status={item.status==='active'?'active':item.status==='pending'?'beta':'maintenance'}/><div className="benefitAdminActions">{item.status!=='active'&&<button onClick={()=>moderateBusiness(item.id,'active',item.verified)}>Aprobar</button>}{item.status==='active'&&<button onClick={()=>moderateBusiness(item.id,'suspended',item.verified)}>Suspender</button>}{!item.verified&&<button onClick={()=>moderateBusiness(item.id,item.status,true)}>Verificar</button>}<button className="dangerButton" onClick={()=>moderateBusiness(item.id,'rejected',false)}>Rechazar</button></div></article>)}</div></Card><Card title="Reclamos de propiedad" icon="✅"><div className="benefitAdminList">{commerceSnapshot.business_claims.length?commerceSnapshot.business_claims.map(claim=>{const business=commerceSnapshot.businesses.find(x=>x.id===claim.business_id);return <article key={claim.id}><div><b>{business?.name||'Negocio'}</b><span>@{(commerceSnapshot.businesses.find(x=>x.id===claim.business_id)?.owner?.username)||'solicitante'} · {claim.evidence||'Sin evidencia escrita'}</span></div><StatusPill status={claim.status==='approved'?'active':claim.status==='pending'?'beta':'maintenance'}/><div className="benefitAdminActions">{claim.status==='pending'&&<><button onClick={()=>moderateClaim(claim.id,'approved')}>Aprobar</button><button className="dangerButton" onClick={()=>moderateClaim(claim.id,'rejected')}>Rechazar</button></>}</div></article>}):<p className="muted">No hay reclamos registrados.</p>}</div><h3>Reportes</h3><div className="benefitAdminList">{commerceSnapshot.business_reports.length?commerceSnapshot.business_reports.map(report=><article key={report.id}><div><b>{report.reason}</b><span>{report.details||'Sin detalle'}</span></div><StatusPill status={report.status==='resolved'?'active':report.status==='reviewing'?'maintenance':'beta'}/><div className="benefitAdminActions"><button onClick={()=>moderateBusinessReport(report.id,'reviewing')}>Revisar</button><button onClick={()=>moderateBusinessReport(report.id,'resolved')}>Resolver</button></div></article>):<p className="muted">Sin reportes pendientes.</p>}</div></Card></div></>}
 {tab==='market'&&<><div className="adminKpis"><span><b>{commerceSnapshot.listings.length}</b> publicaciones visibles</span><span><b>{commerceSnapshot.pendingListingCount}</b> pendientes</span><span><b>{commerceSnapshot.pendingListingReportCount}</b> reportes</span><span><b>{commerceSnapshot.listings.filter(x=>x.verified).length}</b> verificadas</span></div>{maintenanceMessage&&<p className="accountMessage">{maintenanceMessage}</p>}<div className="grid2"><Card title="Moderación Marketplace local" icon="🛒"><div className="benefitAdminList">{commerceSnapshot.listings.slice().sort((a,b)=>(a.status==='pending'?-1:1)-(b.status==='pending'?-1:1)).map(item=><article key={item.id}><div><b>{item.title}</b><span>@{item.seller_username} · S/ {Number(item.price).toFixed(2)} · {item.views||0} vistas</span></div><StatusPill status={item.status==='active'?'active':item.status==='pending'?'beta':'maintenance'}/><div className="benefitAdminActions">{item.status!=='active'&&<button onClick={()=>moderateListing(item.id,'active',true)}>Aprobar</button>}{item.status==='active'&&<button onClick={()=>moderateListing(item.id,'paused',item.verified)}>Pausar</button>}<button className="dangerButton" onClick={()=>moderateListing(item.id,'rejected',false)}>Rechazar</button></div></article>)}</div></Card><Card title="Reportes Marketplace" icon="🚩"><div className="benefitAdminList">{commerceSnapshot.listing_reports.length?commerceSnapshot.listing_reports.map(report=>{const item=commerceSnapshot.listings.find(x=>x.id===report.listing_id);return <article key={report.id}><div><b>{report.reason}</b><span>{item?.title||'Publicación'} · {report.details||'Sin detalle'}</span></div><StatusPill status={report.status==='resolved'||report.status==='dismissed'?'active':report.status==='reviewing'?'maintenance':'beta'}/><div className="benefitAdminActions"><button onClick={()=>moderateListingReport(report.id,'reviewing')}>Revisar</button><button onClick={()=>moderateListingReport(report.id,'resolved')}>Resolver</button><button onClick={()=>moderateListingReport(report.id,'dismissed')}>Descartar</button></div></article>}):<p className="muted">No hay reportes locales.</p>}</div><Card title="Políticas activas" icon="🛡️"><ul className="list compact"><li>Productos ilegales, peligrosos o falsificados están prohibidos.</li><li>El número telefónico no se muestra públicamente.</li><li>El contacto requiere solicitud aceptada en MiZona Chat.</li><li>Los usuarios pueden pausar o marcar vendidos sus avisos.</li></ul></Card></Card></div></>}
 {tab==='campus'&&<><div className="adminKpis"><span><b>24</b> cursos</span><span><b>2,840</b> estudiantes</span><span><b>16</b> certificados emitidos</span><span><b>3</b> revisiones pendientes</span></div><div className="grid2"><Card title="Gestión de cursos" icon="🎓"><div className="adminTable">{campusCourses.map(c=><div key={c.title}><b>{c.title}</b><span>{c.teacher} · {c.students} estudiantes</span><StatusPill status={c.status}/><button>Administrar</button></div>)}</div></Card><Card title="Políticas educativas" icon="🛡️"><ul className="list"><li>Profesores y cursos requieren revisión previa.</li><li>Los certificados usan código verificable.</li><li>El progreso se guarda por usuario y curso.</li><li>Los cursos escolares no habilitan chat externo.</li><li>Materiales y videos deben respetar derechos de autor.</li><li>El administrador puede activar, pausar u ocultar cursos.</li></ul></Card></div></>}
 {tab==='businessSuite'&&<><div className="adminKpis"><span><b>18</b> negocios activos</span><span><b>7</b> sedes</span><span><b>1,284</b> ventas hoy</span><span><b>3</b> alertas</span></div><div className="grid2"><Card title="Negocios conectados" icon="🧾"><div className="adminTable"><div><b>Pollería Mi Zona Centro</b><span>Pachacútec · plan inicial</span><StatusPill status="active"/><button>Administrar</button></div><div><b>Bodega Los Pinos</b><span>Ventanilla · configuración</span><StatusPill status="beta"/><button>Revisar</button></div><div><b>Salón Luz</b><span>Mi Perú · suspendido</span><StatusPill status="maintenance"/><button>Abrir</button></div></div></Card><Card title="Controles empresariales" icon="🛡️"><ul className="list"><li>Todos los datos se separan por negocio y sede.</li><li>Caja, cocina e inventario usan permisos por empleado.</li><li>Las ventas guardan subtotal, IGV, pago y vuelto.</li><li>Los comprobantes se generan solo después de confirmar el cobro.</li><li>El administrador puede suspender un negocio sin afectar a los demás.</li></ul></Card></div></>}
 {tab==='rideAdmin'&&<><div className="adminKpis"><span><b>86</b> conductores</span><span><b>92</b> viajes hoy</span><span><b>14</b> envíos</span><span><b>2</b> revisiones</span></div><div className="grid2"><Card title="Conductores y vehículos" icon="🚗"><div className="adminTable"><div><b>Luis Mendoza</b><span>Toyota Yaris · documentos vigentes</span><StatusPill status="active"/><button>Verificar</button></div><div><b>Carlos Rojas</b><span>Hyundai Accent · renovación pendiente</span><StatusPill status="beta"/><button>Revisar</button></div><div><b>Ana Torres</b><span>Moto Honda · activa</span><StatusPill status="active"/><button>Abrir</button></div></div></Card><Card title="Seguridad de movilidad" icon="🛡️"><ul className="list"><li>Conductores y vehículos requieren validación documental.</li><li>Cada viaje mantiene eventos, conductor y pasajero vinculados.</li><li>El código de seguridad se usa antes de iniciar.</li><li>Los teléfonos no se muestran públicamente.</li><li>Reportes graves bloquean temporalmente al conductor.</li></ul></Card></div></>}
 {tab==='aiAdmin'&&<><div className="adminKpis"><span><b>1,462</b> consultas</span><span><b>78%</b> resueltas</span><span><b>14</b> alertas</span><span><b>0</b> claves expuestas</span></div><div className="grid2"><Card title="Uso del asistente" icon="✨"><div className="adminTable"><div><b>Comunidad</b><span>Comunicación y organización</span><StatusPill status="active"/><button>Configurar</button></div><div><b>Negocios</b><span>Ventas, promociones e inventario</span><StatusPill status="active"/><button>Configurar</button></div><div><b>Educación</b><span>Rutas y orientación de cursos</span><StatusPill status="active"/><button>Configurar</button></div></div></Card><Card title="Protecciones de IA" icon="🛡️"><ul className="list"><li>Las claves de proveedores se guardan únicamente en el servidor.</li><li>Las conversaciones sensibles pueden excluirse del historial.</li><li>El sistema muestra advertencias para datos privados y menores.</li><li>Las respuestas médicas, legales o financieras requieren fuentes y advertencias.</li><li>El administrador controla límites, costos y categorías permitidas.</li></ul></Card></div></>}

 {tab==='chatReports'&&<><div className="adminKpis"><span><b>{chatReports.filter(r=>r.status==='pending').length}</b> pendientes</span><span><b>{chatReports.filter(r=>r.status==='reviewing').length}</b> revisando</span><span><b>{chatReports.filter(r=>r.status==='resolved').length}</b> resueltos</span><span><b>7 días</b> retención</span></div><Card title="Reportes de MiZona Chat" icon="💬"><p className="muted">{backendConnected?'Fuente: Supabase':'Fuente: almacenamiento local de este dispositivo'}</p>{chatReportMessage&&<p className="muted">{chatReportMessage}</p>}<div className="adminTable">{chatReports.length?chatReports.map(r=><div key={r.id}><b>{r.reason}</b><span>{r.details||'Sin detalle'} · {new Date(r.created_at).toLocaleString('es-PE')}</span><StatusPill status={r.status==='pending'?'beta':r.status==='resolved'?'active':'maintenance'}/><button onClick={()=>reviewChatReport(r.id,r.status==='pending'?'reviewing':'resolved')}>{r.status==='pending'?'Revisar':'Resolver'}</button></div>):<p className="muted">No hay reportes pendientes.</p>}</div></Card></>}

 {tab==='contingency'&&<><div className="adminKpis"><span><b>{localStats.contacts}</b> contactos</span><span><b>{localStats.conversations}</b> conversaciones</span><span><b>{localStats.messages}</b> mensajes</span><span><b>{localStats.syncPending}</b> acciones locales</span></div><div className="grid2"><Card title="Estado de contingencia" icon="📦"><div className="contingencyStatus"><span><b>Modo de datos</b><em>{dataMode==='local'?'Local':'Nube solicitada'}</em></span><span><b>Internet</b><em>{online?'Disponible':'Sin conexión'}</em></span><span><b>Último cambio</b><em>{new Date(localStats.updatedAt).toLocaleString('es-PE')}</em></span><span><b>Reportes pendientes</b><em>{localStats.reportsPending}</em></span></div>{maintenanceMessage&&<p className="accountMessage">{maintenanceMessage}</p>}<div className="contingencyActions"><button onClick={exportLocalBackup}>Descargar respaldo JSON</button><button onClick={runCleanup}>Eliminar contenido vencido</button><button className="dangerButton" onClick={resetLocal}>Restablecer datos locales</button></div></Card><Card title="Cola para sincronización futura" icon="🔄"><p className="muted">Estas acciones permanecen en el dispositivo hasta que se diseñe la sincronización segura con el backend.</p><div className="queueList">{syncQueue.slice(0,12).map(item=><div key={item.id}><b>{item.action}</b><span>{item.entity_type} · {new Date(item.created_at).toLocaleString('es-PE')}</span><em>{item.status}</em></div>)}{!syncQueue.length&&<p className="muted">No hay acciones pendientes.</p>}</div></Card></div></>}
 {tab==='audit'&&<Card title="Auditoría local" icon="🧾"><p className="muted">Registro de cambios realizados en este navegador. No reemplaza una auditoría de servidor.</p><div className="auditList">{auditLogs.slice(0,80).map(log=><div key={log.id}><b>{log.action}</b><span>{log.entity_type} · {log.entity_id}</span><small>{log.detail||'Sin detalle'} · {new Date(log.created_at).toLocaleString('es-PE')}</small></div>)}</div></Card>}

 {tab==='security'&&<div className="grid2"><Card title="Reglas escolares" icon="🏫"><ul className="list"><li>Alumnos solo interactúan dentro de su colegio.</li><li>Búsqueda por usuario exacto.</li><li>Sin videollamadas escolares en esta fase.</li><li>Grupos de trabajo permitidos y moderables.</li></ul></Card><Card title="Control antifraude" icon="🔎"><ul className="list"><li>Alerta por creación masiva de cuentas.</li><li>Revisión de campañas engañosas.</li><li>Registro de reportes, bloqueos y suspensiones.</li><li>Validación adicional para administradores y negocios.</li></ul></Card></div>}
 {tab==='storage'&&<Card title="Storage y mantenimiento" icon="🧹"><div className="progressRows"><label>Storage usado <b>21%</b><i><span style={{width:'21%'}}/></i></label><label>Chats por vencer <b>126</b><i><span style={{width:'40%'}}/></i></label><label>Archivos temporales <b>62</b><i><span style={{width:'30%'}}/></i></label><label>Imágenes de beneficios <b>38</b><i><span style={{width:'24%'}}/></i></label></div></Card>}
 </div>;
}
