import { useMemo, useState } from 'react';
import Card from '../components/Card';
import StatusPill from '../components/StatusPill';
import Tabs from '../components/Tabs';
import { useApp } from '../context/AppContext';

const campaigns=[
 {id:1,title:'Combo familiar de pollo',owner:'Pollería El Buen Sabor',type:'Oferta',status:'active',views:1260,actions:184},
 {id:2,title:'Campaña médica gratuita',owner:'Centro de Salud Pachacútec',type:'Campaña',status:'active',views:840,actions:92},
 {id:3,title:'Auxiliar de caja',owner:'Mercado Central',type:'Empleo',status:'beta',views:610,actions:47},
 {id:4,title:'2x1 entradas infantiles',owner:'Cine Plaza Ventanilla',type:'Cupón',status:'maintenance',views:430,actions:68}
];

const campusCourses=[
 {title:'Excel desde cero',teacher:'Daniela Ramos',students:1284,status:'active'},
 {title:'Power BI para principiantes',teacher:'Marco Salazar',students:716,status:'beta'},
 {title:'Matemática práctica secundaria',teacher:'Luis Medina',students:493,status:'active'},
 {title:'Vende más en tu zona',teacher:'Carla Torres',students:362,status:'maintenance'}
];

export default function Admin(){
 const { moduleConfig, updateModuleStatus, resetModules } = useApp();
 const [tab,setTab]=useState('modules');
 const [campaignState,setCampaignState]=useState(campaigns);
 const counts=useMemo(()=>moduleConfig.reduce((a,m)=>({...a,[m.status]:(a[m.status]||0)+1}),{}),[moduleConfig]);
 const cycle=s=>s==='active'?'beta':s==='beta'?'maintenance':s==='maintenance'?'soon':'active';
 const toggleCampaign=id=>setCampaignState(arr=>arr.map(x=>x.id===id?{...x,status:x.status==='active'?'maintenance':'active'}:x));
 const tabs=[{id:'modules',label:'Módulos',icon:'🧩'},{id:'benefits',label:'Beneficios',icon:'🎁'},{id:'places',label:'Negocios',icon:'🏪'},{id:'market',label:'Marketplace',icon:'🛒'},{id:'campus',label:'CampusHugo',icon:'🎓'},{id:'businessSuite',label:'MiZona Business',icon:'🧾'},{id:'rideAdmin',label:'MiZona Ride',icon:'🚗'},{id:'aiAdmin',label:'IA MiZona',icon:'✨'},{id:'security',label:'Seguridad',icon:'🛡️'},{id:'storage',label:'Storage',icon:'🧹'}];
 return <div className="page"><h1>Centro de Control Enterprise</h1><p className="muted">Controla módulos, permisos, comunidades, chat, beneficios, storage y evolución de MiZona.</p><div className="stats"><span>🟢 Activos: {counts.active||0}</span><span>🟡 Beta: {counts.beta||0}</span><span>🔴 Mant.: {counts.maintenance||0}</span><span>⚪ Próx.: {counts.soon||0}</span></div><Tabs tabs={tabs} active={tab} setActive={setTab}/>
 {tab==='modules'&&<div className="grid2"><Card title="Control de módulos" icon="🧩"><div className="adminTable">{moduleConfig.map((m)=><div key={m.id}><b>{m.label}</b><span>{m.audience}</span><StatusPill status={m.status}/><button onClick={()=>updateModuleStatus(m.id,cycle(m.status))}>Cambiar</button></div>)}</div><button className="ghost" onClick={resetModules}>Restablecer estados</button></Card><Card title="Políticas activas" icon="🛡"><ul className="list"><li>No chat entre colegios.</li><li>Aula Chat solo con alumnos validados.</li><li>Chats y archivos vencen en 7 días.</li><li>Usuario único y nombres no vulgares.</li><li>Adultos no buscan escolares.</li><li>Beneficios requieren fecha de vigencia y responsable.</li></ul></Card></div>}
 {tab==='benefits'&&<><div className="adminKpis"><span><b>3,140</b> vistas</span><span><b>391</b> acciones</span><span><b>12.5%</b> conversión</span><span><b>4</b> campañas</span></div><Card title="Moderación de oportunidades" icon="🎁"><div className="campaignTable"><div className="campaignRow campaignHead"><b>Campaña</b><b>Responsable</b><b>Tipo</b><b>Resultados</b><b>Estado</b><b>Acción</b></div>{campaignState.map(c=><div className="campaignRow" key={c.id}><b>{c.title}</b><span>{c.owner}</span><span>{c.type}</span><span>{c.views} vistas · {c.actions} acciones</span><StatusPill status={c.status}/><button onClick={()=>toggleCampaign(c.id)}>{c.status==='active'?'Pausar':'Activar'}</button></div>)}</div></Card></>}

 {tab==='places'&&<><div className="adminKpis"><span><b>248</b> lugares</span><span><b>36</b> afiliados</span><span><b>7</b> reclamos pendientes</span><span><b>14</b> sugerencias</span></div><div className="grid2"><Card title="Reclamos pendientes" icon="✅"><div className="adminTable"><div><b>Lolita Burger</b><span>José Ramírez · evidencia adjunta</span><StatusPill status="beta"/><button>Abrir</button></div><div><b>Ferretería Don Carlos</b><span>Carlos Mendoza · documento enviado</span><StatusPill status="beta"/><button>Abrir</button></div><div><b>Salón Luz</b><span>María Torres · revisión pendiente</span><StatusPill status="maintenance"/><button>Revisar</button></div></div></Card><Card title="Reglas de publicación" icon="🛡️"><ul className="list"><li>Todos los lugares activos pueden aparecer con información básica.</li><li>Solo el dueño verificado administra promociones y contacto.</li><li>Los aportes vecinales pasan por moderación.</li><li>Los duplicados deben fusionarse, no crear fichas nuevas.</li><li>Las acciones de ruta, llamada, cupón y chat quedan registradas.</li></ul></Card></div></>}

 {tab==='market'&&<><div className="adminKpis"><span><b>326</b> publicaciones</span><span><b>21</b> pendientes</span><span><b>9</b> reportes</span><span><b>91</b> vendedores verificados</span></div><div className="grid2"><Card title="Moderación Marketplace" icon="🛒"><div className="adminTable"><div><b>Tablet Samsung 10 pulgadas</b><span>Reporte: posible descripción incompleta</span><StatusPill status="beta"/><button>Revisar</button></div><div><b>Servicio de reparación express</b><span>Validar categoría y datos del vendedor</span><StatusPill status="maintenance"/><button>Revisar</button></div><div><b>Mochila escolar nueva</b><span>Publicación aprobada</span><StatusPill status="active"/><button>Ocultar</button></div></div></Card><Card title="Políticas Marketplace" icon="🛡️"><ul className="list"><li>Prohibidos productos ilegales, peligrosos o falsificados.</li><li>Usuarios escolares solo publican dentro de categorías permitidas.</li><li>El número telefónico no se muestra públicamente.</li><li>Los contactos se realizan mediante MiZona Chat.</li><li>Reportes reiterados pueden suspender publicación y cuenta.</li></ul></Card></div></>}
 {tab==='campus'&&<><div className="adminKpis"><span><b>24</b> cursos</span><span><b>2,840</b> estudiantes</span><span><b>16</b> certificados emitidos</span><span><b>3</b> revisiones pendientes</span></div><div className="grid2"><Card title="Gestión de cursos" icon="🎓"><div className="adminTable">{campusCourses.map(c=><div key={c.title}><b>{c.title}</b><span>{c.teacher} · {c.students} estudiantes</span><StatusPill status={c.status}/><button>Administrar</button></div>)}</div></Card><Card title="Políticas educativas" icon="🛡️"><ul className="list"><li>Profesores y cursos requieren revisión previa.</li><li>Los certificados usan código verificable.</li><li>El progreso se guarda por usuario y curso.</li><li>Los cursos escolares no habilitan chat externo.</li><li>Materiales y videos deben respetar derechos de autor.</li><li>El administrador puede activar, pausar u ocultar cursos.</li></ul></Card></div></>}
 {tab==='businessSuite'&&<><div className="adminKpis"><span><b>18</b> negocios activos</span><span><b>7</b> sedes</span><span><b>1,284</b> ventas hoy</span><span><b>3</b> alertas</span></div><div className="grid2"><Card title="Negocios conectados" icon="🧾"><div className="adminTable"><div><b>Pollería Mi Zona Centro</b><span>Pachacútec · plan inicial</span><StatusPill status="active"/><button>Administrar</button></div><div><b>Bodega Los Pinos</b><span>Ventanilla · configuración</span><StatusPill status="beta"/><button>Revisar</button></div><div><b>Salón Luz</b><span>Mi Perú · suspendido</span><StatusPill status="maintenance"/><button>Abrir</button></div></div></Card><Card title="Controles empresariales" icon="🛡️"><ul className="list"><li>Todos los datos se separan por negocio y sede.</li><li>Caja, cocina e inventario usan permisos por empleado.</li><li>Las ventas guardan subtotal, IGV, pago y vuelto.</li><li>Los comprobantes se generan solo después de confirmar el cobro.</li><li>El administrador puede suspender un negocio sin afectar a los demás.</li></ul></Card></div></>}
 {tab==='rideAdmin'&&<><div className="adminKpis"><span><b>86</b> conductores</span><span><b>92</b> viajes hoy</span><span><b>14</b> envíos</span><span><b>2</b> revisiones</span></div><div className="grid2"><Card title="Conductores y vehículos" icon="🚗"><div className="adminTable"><div><b>Luis Mendoza</b><span>Toyota Yaris · documentos vigentes</span><StatusPill status="active"/><button>Verificar</button></div><div><b>Carlos Rojas</b><span>Hyundai Accent · renovación pendiente</span><StatusPill status="beta"/><button>Revisar</button></div><div><b>Ana Torres</b><span>Moto Honda · activa</span><StatusPill status="active"/><button>Abrir</button></div></div></Card><Card title="Seguridad de movilidad" icon="🛡️"><ul className="list"><li>Conductores y vehículos requieren validación documental.</li><li>Cada viaje mantiene eventos, conductor y pasajero vinculados.</li><li>El código de seguridad se usa antes de iniciar.</li><li>Los teléfonos no se muestran públicamente.</li><li>Reportes graves bloquean temporalmente al conductor.</li></ul></Card></div></>}
 {tab==='aiAdmin'&&<><div className="adminKpis"><span><b>1,462</b> consultas</span><span><b>78%</b> resueltas</span><span><b>14</b> alertas</span><span><b>0</b> claves expuestas</span></div><div className="grid2"><Card title="Uso del asistente" icon="✨"><div className="adminTable"><div><b>Comunidad</b><span>Comunicación y organización</span><StatusPill status="active"/><button>Configurar</button></div><div><b>Negocios</b><span>Ventas, promociones e inventario</span><StatusPill status="active"/><button>Configurar</button></div><div><b>Educación</b><span>Rutas y orientación de cursos</span><StatusPill status="active"/><button>Configurar</button></div></div></Card><Card title="Protecciones de IA" icon="🛡️"><ul className="list"><li>Las claves de proveedores se guardan únicamente en el servidor.</li><li>Las conversaciones sensibles pueden excluirse del historial.</li><li>El sistema muestra advertencias para datos privados y menores.</li><li>Las respuestas médicas, legales o financieras requieren fuentes y advertencias.</li><li>El administrador controla límites, costos y categorías permitidas.</li></ul></Card></div></>}
 {tab==='security'&&<div className="grid2"><Card title="Reglas escolares" icon="🏫"><ul className="list"><li>Alumnos solo interactúan dentro de su colegio.</li><li>Búsqueda por usuario exacto.</li><li>Sin videollamadas escolares en esta fase.</li><li>Grupos de trabajo permitidos y moderables.</li></ul></Card><Card title="Control antifraude" icon="🔎"><ul className="list"><li>Alerta por creación masiva de cuentas.</li><li>Revisión de campañas engañosas.</li><li>Registro de reportes, bloqueos y suspensiones.</li><li>Validación adicional para administradores y negocios.</li></ul></Card></div>}
 {tab==='storage'&&<Card title="Storage y mantenimiento" icon="🧹"><div className="progressRows"><label>Storage usado <b>21%</b><i><span style={{width:'21%'}}/></i></label><label>Chats por vencer <b>126</b><i><span style={{width:'40%'}}/></i></label><label>Archivos temporales <b>62</b><i><span style={{width:'30%'}}/></i></label><label>Imágenes de beneficios <b>38</b><i><span style={{width:'24%'}}/></i></label></div></Card>}
 </div>;
}
