import { useState } from 'react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import StatusPill from '../components/StatusPill';
import { communities, notices, schoolRooms } from '../data/modules';

const tabs = [
  {id:'overview', label:'Inicio', icon:'🏘'}, {id:'schools', label:'Colegios', icon:'🏫'}, {id:'committees', label:'Comités', icon:'📋'}, {id:'events', label:'Eventos', icon:'📅'}, {id:'docs', label:'Documentos', icon:'📁'}, {id:'admin', label:'Admin', icon:'⚙️'}
];

export default function Community({ setPage }) {
  const [tab,setTab] = useState('overview');
  return <div className="page"><div className="pageTitle"><div><h1>Mi Comunidad</h1><p className="muted">Primer motor de usuarios: colegios, comités, clubes y urbanizaciones.</p></div><button className="primary">+ Solicitar comunidad</button></div><Tabs tabs={tabs} active={tab} setActive={setTab}/>{tab==='overview'&&<Overview setPage={setPage}/>} {tab==='schools'&&<Schools setPage={setPage}/>} {tab==='committees'&&<Committees/>} {tab==='events'&&<Events/>} {tab==='docs'&&<Docs setPage={setPage}/>} {tab==='admin'&&<CommunityAdmin/>}</div>;
}
function Overview({setPage}){return <div className="grid3">{communities.map(c=><Card key={c.id} title={c.name} icon={c.type==='Colegio'?'🏫':c.type==='Comité'?'📋':'⚽'}><p className="muted">{c.type} · {c.zone}</p><p><b>{c.members}</b> miembros potenciales</p><div className="chips">{c.features.map(f=><span key={f}>{f}</span>)}</div><StatusPill status={c.status}/><button className="primary" onClick={()=>c.type==='Colegio'?setPage('school'):null}>Abrir</button></Card>)}</div>}
function Schools({setPage}){return <div className="grid2"><Card title="Colegio San Martín" icon="🏫"><p>Comunidad modelo para iniciar usuarios por colegio.</p><ul className="list"><li>Comunicados oficiales</li><li>Aula Chat por salón</li><li>MiZona Transfer 7 días</li><li>Eventos y documentos</li></ul><button className="primary" onClick={()=>setPage('school')}>Entrar al colegio</button></Card><Card title="Crear colegio" icon="➕"><input className="field" placeholder="Nombre del colegio"/><input className="field" placeholder="Distrito / zona"/><select className="field"><option>Inicial</option><option>Primaria</option><option>Secundaria</option><option>Completo</option></select><button className="primary full">Solicitar aprobación</button></Card></div>}
function Committees(){return <div className="grid2"><Card title="Comité vecinal" icon="📋"><p>Actas, avisos, eventos y documentos de vecinos.</p><button className="primary">Crear comité</button></Card><Card title="Reglas" icon="🛡"><ul className="list"><li>Solo administradores aprobados publican comunicados.</li><li>Miembros por invitación o código.</li><li>Documentos organizados por carpeta.</li></ul></Card></div>}
function Events(){return <div className="timeline">{notices.map(n=><div key={n.title} className="timelineItem"><b>{n.title}</b><span>{n.category} · {n.date} · {n.target}</span><button>Compartir / Difundir</button></div>)}</div>}
function Docs({setPage}){return <div className="grid2"><Card title="Documentos escolares" icon="📁"><ul className="list"><li>Comunicado reunión.pdf</li><li>Lista de útiles.xlsx</li><li>Actividad deportiva.docx</li></ul></Card><Card title="Archivo pesado" icon="📤"><p>Usa MiZona Transfer para archivos temporales de 7 días.</p><button className="primary" onClick={()=>setPage('transfer')}>Abrir Transfer</button></Card></div>}
function CommunityAdmin(){return <Card title="Administración de comunidad" icon="⚙️"><div className="adminGrid"><label><input type="checkbox" defaultChecked/> Comunicados activos</label><label><input type="checkbox" defaultChecked/> Aula Chat activo</label><label><input type="checkbox" defaultChecked/> Transfer temporal 7 días</label><label><input type="checkbox"/> Videollamadas desactivadas</label></div></Card>}
export function SchoolPage({setPage}){return <div className="page"><div className="pageTitle"><div><h1>🏫 Colegio San Martín</h1><p className="muted">Comunidad escolar controlada por administradores y profesores.</p></div><button className="ghost" onClick={()=>setPage('community')}>Volver</button></div><div className="grid2"><Card title="Comunicados" icon="📢"><ul className="list">{notices.map(n=><li key={n.title}>{n.title} · {n.date}</li>)}</ul></Card><Card title="Aulas activas" icon="💬"><div className="moduleMini">{schoolRooms.map(r=><div key={r.id}><b>{r.name}</b><span>{r.teacher}</span><span>{r.members} alumnos</span><button onClick={()=>setPage('chat')}>Chat</button></div>)}</div></Card></div><Card title="Funciones escolares" icon="🧩"><div className="quickGrid"><button className="quick">📢 Comunicados</button><button className="quick">📅 Eventos</button><button className="quick">📁 Documentos</button><button className="quick" onClick={()=>setPage('transfer')}>📤 Transfer</button><button className="quick">👨‍🏫 Profesores</button><button className="quick">⚙️ Configuración</button></div></Card></div>}
