import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckCircle2,ChevronRight,Download,FileText,Megaphone,Plus,Printer,ReceiptText,Send,Settings,Trash2,Users,WalletCards} from 'lucide-react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import {useApp} from '../context/AppContext';
import {isStudentProfile} from '../lib/permissions';
import {addAnnouncement,addCampaign,addDocument,addEvent,addExpense,addFamily,addMember,addMinute,addPayment,getCommitteeFinance,markReminder,removeRecord,setAllCampaignParticipants,subscribeCommitteeFinance,toggleCampaign,toggleCampaignParticipant,updateCommittee} from '../lib/localCommittees';

const money=v=>`S/ ${Number(v||0).toFixed(2)}`;
const csv=(name,rows)=>{const text=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const downloadJson=data=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='respaldo-comite-mizona.json';a.click();URL.revokeObjectURL(a.href)};
const initials=name=>String(name||'?').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();

export default function Committees({setPage}){
 const {profile}=useApp();
 const [data,setData]=useState(getCommitteeFinance);
 const [tab,setTabState]=useState(()=>window.history.state?.committeeTab||'dashboard');
 const [notice,setNotice]=useState('');
 const [campaign,setCampaign]=useState({name:'',category:'',amount:'',dueDate:'',description:''});
 const [payment,setPayment]=useState({familyId:'',campaignId:'',amount:'',method:'Yape',reference:'',receiptName:''});
 const [expense,setExpense]=useState({campaignId:'',concept:'',detail:'',amount:'',responsible:'',receipt:'',receiptName:''});
 const [family,setFamily]=useState({student:'',guardian:'',phone:''});
 const [announcement,setAnnouncement]=useState({title:'',body:'',audience:'Familias del aula',published:true});
 const [event,setEvent]=useState({title:'',date:'',time:'',place:'',description:'',publishHome:true});
 const [minute,setMinute]=useState({title:'',date:'',summary:'',agreements:'',fileName:''});
 const [document,setDocument]=useState({title:'',category:'Comprobante',fileName:'',note:''});
 const [member,setMember]=useState({name:'',role:'Vocal',phone:''});
 const [activeCampaignId,setActiveCampaignId]=useState('');

 useEffect(()=>subscribeCommitteeFinance(setData),[]);
 useEffect(()=>{if(!activeCampaignId&&data.campaigns[0])setActiveCampaignId(data.campaigns[0].id)},[activeCampaignId,data.campaigns]);
 useEffect(()=>{
  const onPop=e=>{if(e.state?.mzPage==='committees'&&e.state?.committeeTab)setTabState(e.state.committeeTab)};
  window.addEventListener('popstate',onPop);
  return()=>window.removeEventListener('popstate',onPop);
 },[]);
 const goTab=id=>{setTabState(id);try{window.history.pushState({mzPage:'committees',committeeTab:id},'',`#committees/${id}`)}catch{}};

 const participantIds=campaign=>Array.isArray(campaign?.participantIds)?campaign.participantIds:data.families.map(f=>f.id);
 const isParticipant=(campaign,familyId)=>participantIds(campaign).includes(familyId);
 const campaignById=id=>data.campaigns.find(c=>c.id===id);
 const activeCampaign=campaignById(activeCampaignId)||data.campaigns[0];
 const activeParticipantIds=participantIds(activeCampaign);
 const paid=(familyId,campaignId)=>data.payments.filter(p=>p.familyId===familyId&&p.campaignId===campaignId).reduce((s,p)=>s+Number(p.amount),0);
 const status=(family,campaign)=>{if(!isParticipant(campaign,family.id))return 'No participa';const x=paid(family.id,campaign.id);return x>=Number(campaign.amount)?'Pagado':x>0?'Parcial':'Pendiente'};
 const summary=useMemo(()=>{const expected=data.campaigns.reduce((s,c)=>s+Number(c.amount)*participantIds(c).length,0);const collected=data.payments.reduce((s,p)=>s+Number(p.amount),0);const spent=data.expenses.reduce((s,e)=>s+Number(e.amount),0);return{expected,collected,spent,balance:collected-spent,pending:Math.max(0,expected-collected),families:data.families.length,activities:data.campaigns.filter(c=>c.status==='active').length,participants:activeParticipantIds.length}},[data,activeParticipantIds.length]);

 if(isStudentProfile(profile))return <div className="page"><Card title="Acceso protegido" icon="🛡️"><p>La administración del comité solo está disponible para adultos responsables.</p><button className="primary" onClick={()=>setPage('campus')}>Volver</button></Card></div>;
 const notify=(f,c)=>{markReminder(f.id,c.id);setNotice(`Recordatorio preparado para ${f.guardian}: ${c.name} · ${money(Number(c.amount)-paid(f.id,c.id))} pendiente.`)};
 const tabs=[['dashboard','Inicio','🏠'],['families','Participantes','👥'],['campaigns','Cuotas','🧾'],['matrix','Quién pagó','✅'],['payments','Ingresos','💳'],['expenses','Gastos','💸'],['announcements','Comunicados','📣'],['events','Eventos','📅'],['minutes','Actas','📝'],['documents','Documentos','📁'],['reports','Reportes','📈'],['settings','Configuración','⚙️']].map(([id,label,icon])=>({id,label,icon}));

 return <div className="page committeeFinancePage improvedCommitteePage">
  <section className="committeeHero newCommitteeHero">
   <div className="committeeHeroIcon"><Users size={34}/></div>
   <div><p className="eyebrow">Comité escolar</p><h1>{data.committee.name}</h1><p>{data.committee.classroom} · Gestión de cuotas, participantes, comunicados y rendición {data.committee.period}.</p></div>
   <span className="committeeState">● Activa</span>
  </section>
  {notice&&<div className="localModeStrip"><Send size={18}/><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
  <Tabs active={tab} setActive={goTab} tabs={tabs}/>

  {tab==='dashboard'&&<>
   <div className="committeeKpis"><span><b>{money(summary.expected)}</b><small>Total esperado</small></span><span><b>{money(summary.collected)}</b><small>Total cobrado</small></span><span><b>{money(summary.spent)}</b><small>Gastos</small></span><span><b>{money(summary.balance)}</b><small>Saldo real</small></span></div>
   <div className="grid2"><Card title="Orden recomendado" icon="🧭"><div className="workflowList">{tabs.filter(t=>['families','campaigns','matrix','payments','expenses','announcements','reports','settings'].includes(t.id)).map((t,i)=><button key={t.id} onClick={()=>goTab(t.id)}><b>{i+1}</b><span>{t.icon} {t.label}</span><ChevronRight size={16}/></button>)}</div></Card><Card title="Actividad principal" icon="📌"><div className="dataList">{data.campaigns.filter(c=>c.status==='active').map(c=><article key={c.id}><div><b>{c.name}</b><span>{c.category} · {participantIds(c).length} participantes · vence {c.dueDate}</span></div><strong>{money(c.amount)}</strong></article>)}</div></Card></div>
   <div className="grid2"><Card title="Último comunicado" icon="📣"><div className="dataList">{data.announcements.slice(0,2).map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.body}</span><small>{a.audience} · {a.published?'Publicado':'Borrador'}</small></div></article>)}</div><button className="primary" onClick={()=>goTab('announcements')}><Megaphone size={16}/> Publicar comunicado</button></Card><Card title="Transparencia" icon="🔎"><p><b>{summary.families}</b> familias registradas, <b>{summary.activities}</b> actividades abiertas y <b>{data.expenses.length}</b> gastos documentados.</p><button onClick={()=>goTab('reports')}><Download size={16}/> Ver rendición de cuentas</button></Card></div>
  </>}

  {tab==='families'&&<>
   <Card title="Participantes por cuota o actividad" icon="👥"><p className="muted">Selecciona un concepto y marca quién participa. Solo a esas familias se les cobrará esa cuota.</p><div className="committeeToolbar"><select value={activeCampaign?.id||''} onChange={e=>setActiveCampaignId(e.target.value)}>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {money(c.amount)}</option>)}</select><button onClick={()=>setAllCampaignParticipants(activeCampaign.id,true)}>Todos participan</button><button onClick={()=>setAllCampaignParticipants(activeCampaign.id,false)}>Nadie participa</button></div><div className="participantGrid">{data.families.map(f=><button key={f.id} className={isParticipant(activeCampaign,f.id)?'participant selected':'participant'} onClick={()=>toggleCampaignParticipant(activeCampaign.id,f.id)}><span>{initials(f.student)}</span><div><b>{f.student}</b><small>{f.guardian} · {f.phone}</small></div><em>{isParticipant(activeCampaign,f.id)?'Participa':'No participa'}</em></button>)}</div><p className="participantSummary"><b>{activeParticipantIds.length}</b> participan · <b>{data.families.length-activeParticipantIds.length}</b> no participan en {activeCampaign?.name}.</p></Card>
   <div className="grid2"><Card title="Agregar alumno y apoderado" icon="👨‍👩‍👧"><div className="committeeForm labeled"><label>Nombre del alumno<input placeholder="Ejemplo: Adair Alexander" value={family.student} onChange={e=>setFamily({...family,student:e.target.value})}/></label><label>Nombre del apoderado<input placeholder="Ejemplo: José Salazar" value={family.guardian} onChange={e=>setFamily({...family,guardian:e.target.value})}/></label><label>Celular del apoderado<input placeholder="Ejemplo: 929347128" value={family.phone} onChange={e=>setFamily({...family,phone:e.target.value})}/></label><button className="primary" onClick={()=>{if(!family.student)return;addFamily(family);setFamily({student:'',guardian:'',phone:''})}}><Users size={16}/> Agregar familia</button></div></Card><Card title="Junta directiva" icon="🏛️"><div className="committeeForm labeled"><label>Nombre completo<input placeholder="Ejemplo: Katia" value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/></label><label>Cargo<select value={member.role} onChange={e=>setMember({...member,role:e.target.value})}><option>Presidenta</option><option>Tesorera</option><option>Secretario</option><option>Vocal</option><option>Delegado</option></select></label><label>Celular<input placeholder="Ejemplo: 932530200" value={member.phone} onChange={e=>setMember({...member,phone:e.target.value})}/></label><button onClick={()=>{if(!member.name)return;addMember(member);setMember({name:'',role:'Vocal',phone:''})}}>Agregar cargo</button></div></Card></div>
  </>}

  {tab==='campaigns'&&<div className="grid2"><Card title="Crear cuota o actividad" icon="➕"><div className="committeeForm labeled"><label>Nombre del concepto<input placeholder="Ejemplo: Vestimenta danza" value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/></label><label>Categoría<input placeholder="Ejemplo: Actividad escolar, cumpleaños, paseo" value={campaign.category} onChange={e=>setCampaign({...campaign,category:e.target.value})}/></label><label>Monto por participante<input type="number" placeholder="Ejemplo: 55" value={campaign.amount} onChange={e=>setCampaign({...campaign,amount:e.target.value})}/></label><label>Fecha límite<input type="date" value={campaign.dueDate} onChange={e=>setCampaign({...campaign,dueDate:e.target.value})}/></label><label>Detalle<textarea placeholder="Explica para qué se usará la cuota" value={campaign.description} onChange={e=>setCampaign({...campaign,description:e.target.value})}/></label><button className="primary" onClick={()=>{if(!campaign.name||!campaign.amount)return;addCampaign({...campaign,amount:Number(campaign.amount)});setCampaign({name:'',category:'',amount:'',dueDate:'',description:''})}}>Guardar cuota</button></div></Card><Card title="Cuotas registradas" icon="🧾"><div className="committeeTable compact">{data.campaigns.map(c=><article key={c.id}><div><b>{c.name}</b><small>{c.description}</small></div><span>{money(c.amount)}</span><em>{participantIds(c).length} participantes</em><button onClick={()=>{setActiveCampaignId(c.id);goTab('families')}}>Editar participantes</button><button onClick={()=>toggleCampaign(c.id)}>{c.status==='active'?'Cerrar':'Reabrir'}</button></article>)}</div></Card></div>}

  {tab==='matrix'&&<Card title="Control por alumno y concepto" icon="✅"><div className="conceptSelector"><div><b>Concepto activo:</b> {activeCampaign?.name} · Monto: {money(activeCampaign?.amount)}<small>Solo se cobra a las familias participantes.</small></div><select value={activeCampaign?.id||''} onChange={e=>setActiveCampaignId(e.target.value)}>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="participantStrip"><span>Mostrando {activeParticipantIds.length} de {data.families.length} participantes</span><button onClick={()=>goTab('families')}>Editar participantes</button></div><div className="paymentCards">{data.families.map(f=>{const st=status(f,activeCampaign);const amountPaid=paid(f.id,activeCampaign.id);return <article key={f.id} className={st==='No participa'?'notIncluded':''}><div className="studentAvatar">{initials(f.student)}{st!=='No participa'&&<i><CheckCircle2 size={12}/></i>}</div><div><b>{f.student}</b><small>Apoderado: {f.guardian}<br/>Celular: {f.phone}</small></div><div className="studentPayment"><span className={`matrixStatus ${st.toLowerCase().replace(' ','_')}`}>{st}</span><small>{st==='No participa'?'No se cobra':`${money(amountPaid)} / ${money(activeCampaign.amount)}`}</small>{st==='Pendiente'||st==='Parcial'?<button onClick={()=>notify(f,activeCampaign)}><Send size={14}/> Recordar</button>:null}</div></article>})}</div></Card>}

  {tab==='payments'&&<div className="grid2"><Card title="Registrar ingreso" icon="💳"><div className="committeeForm labeled"><label>Alumno / familia<select value={payment.familyId} onChange={e=>setPayment({...payment,familyId:e.target.value})}><option value="">Selecciona alumno</option>{data.families.map(f=><option key={f.id} value={f.id}>{f.student} · {f.guardian}</option>)}</select></label><label>Concepto<select value={payment.campaignId} onChange={e=>{const c=data.campaigns.find(x=>x.id===e.target.value);setPayment({...payment,campaignId:e.target.value,amount:c?String(c.amount):payment.amount})}}><option value="">Selecciona cuota o actividad</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Monto recibido<input type="number" placeholder="Ejemplo: 55" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Método<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>Yape</option><option>Plin</option><option>Efectivo</option><option>Transferencia</option></select></label><label>Número de operación o recibo<input placeholder="Ejemplo: OP-20391" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><label>Comprobante<input type="file" accept="image/*,.pdf" onChange={e=>setPayment({...payment,receiptName:e.target.files?.[0]?.name||''})}/></label><button className="primary" onClick={()=>{if(!payment.familyId||!payment.campaignId||!payment.amount)return;addPayment({...payment,amount:Number(payment.amount)});setPayment({familyId:'',campaignId:'',amount:'',method:'Yape',reference:'',receiptName:''});setNotice('Pago registrado correctamente.')}}><WalletCards size={16}/> Guardar pago</button></div></Card><Card title="Historial de ingresos" icon="📒"><div className="dataList">{data.payments.map(p=>{const f=data.families.find(x=>x.id===p.familyId);const c=data.campaigns.find(x=>x.id===p.campaignId);return <article key={p.id}><div><b>{f?.student||'Alumno'}</b><span>{c?.name} · {p.method} · {p.reference||'Sin operación'}</span><small>{p.date} {p.receiptName&&`· ${p.receiptName}`}</small></div><strong>{money(p.amount)}</strong></article>})}</div></Card></div>}

  {tab==='expenses'&&<div className="grid2"><Card title="Registrar gasto" icon="💸"><div className="committeeForm labeled"><label>Actividad relacionada<select value={expense.campaignId} onChange={e=>setExpense({...expense,campaignId:e.target.value})}><option value="">Gasto general</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Concepto<input placeholder="Ejemplo: Compra de torta" value={expense.concept} onChange={e=>setExpense({...expense,concept:e.target.value})}/></label><label>Explicación del gasto<textarea placeholder="Detalla por qué se hizo el gasto y qué se compró" value={expense.detail} onChange={e=>setExpense({...expense,detail:e.target.value})}/></label><label>Monto<input type="number" placeholder="Ejemplo: 65" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>Responsable<input placeholder="Ejemplo: Tesorería" value={expense.responsible} onChange={e=>setExpense({...expense,responsible:e.target.value})}/></label><label>Boleta, factura o recibo<input placeholder="Ejemplo: Boleta 001-245" value={expense.receipt} onChange={e=>setExpense({...expense,receipt:e.target.value})}/></label><label>Comprobante<input type="file" accept="image/*,.pdf" onChange={e=>setExpense({...expense,receiptName:e.target.files?.[0]?.name||''})}/></label><button className="primary" onClick={()=>{if(!expense.concept||!expense.amount)return;addExpense({...expense,amount:Number(expense.amount)});setExpense({campaignId:'',concept:'',detail:'',amount:'',responsible:'',receipt:'',receiptName:''})}}>Guardar gasto</button></div></Card><Card title="Gastos documentados" icon="🧾"><div className="committeeTable">{data.expenses.map(e=><article key={e.id}><div><b>{e.concept}</b><small>{e.detail}</small></div><span>{money(e.amount)}</span><em>{e.receipt||'Sin recibo'}</em><button className="danger" onClick={()=>removeRecord('expenses',e.id)}><Trash2 size={14}/></button></article>)}</div></Card></div>}

  {tab==='announcements'&&<div className="grid2"><Card title="Nuevo comunicado" icon="📣"><div className="committeeForm labeled"><label>Título del comunicado<input placeholder="Ejemplo: Celebración del día del maestro" value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></label><label>Mensaje para las familias<textarea placeholder="Escribe fecha, lugar, monto, pedido de opinión o cualquier detalle importante" value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/></label><label>Dirigido a<input placeholder="Ejemplo: Familias del aula" value={announcement.audience} onChange={e=>setAnnouncement({...announcement,audience:e.target.value})}/></label><label className="checkRow"><input type="checkbox" checked={announcement.published} onChange={e=>setAnnouncement({...announcement,published:e.target.checked})}/> Publicar ahora</label><button className="primary" onClick={()=>{if(!announcement.title)return;addAnnouncement(announcement);setAnnouncement({title:'',body:'',audience:'Familias del aula',published:true})}}>Publicar comunicado</button></div></Card><Card title="Comunicados" icon="✉️"><div className="dataList">{data.announcements.map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.body}</span><small>{a.audience} · {a.published?'Publicado':'Borrador'}</small></div></article>)}</div></Card></div>}

  {tab==='events'&&<div className="grid2"><Card title="Nuevo evento" icon="📅"><div className="committeeForm labeled"><label>Nombre del evento<input placeholder="Ejemplo: Compartir por cumpleaños" value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/></label><label>Fecha<input type="date" value={event.date} onChange={e=>setEvent({...event,date:e.target.value})}/></label><label>Hora<input type="time" value={event.time} onChange={e=>setEvent({...event,time:e.target.value})}/></label><label>Lugar<input placeholder="Ejemplo: Aula 4 años" value={event.place} onChange={e=>setEvent({...event,place:e.target.value})}/></label><label>Detalle<textarea placeholder="Describe el evento" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/></label><label className="checkRow"><input type="checkbox" checked={event.publishHome} onChange={e=>setEvent({...event,publishHome:e.target.checked})}/> Mostrar en MiZona</label><button className="primary" onClick={()=>{if(!event.title)return;addEvent(event);setEvent({title:'',date:'',time:'',place:'',description:'',publishHome:true})}}>Guardar evento</button></div></Card><Card title="Eventos" icon="🗓️"><div className="dataList">{data.events.map(e=><article key={e.id}><div><b>{e.title}</b><span>{e.description}</span><small>{e.date} {e.time} · {e.place} · {e.publishHome?'Visible en MiZona':'Interno'}</small></div></article>)}</div></Card></div>}

  {tab==='minutes'&&<div className="grid2"><Card title="Nueva acta" icon="📝"><div className="committeeForm labeled"><label>Título del acta<input placeholder="Ejemplo: Acuerdo de cuota" value={minute.title} onChange={e=>setMinute({...minute,title:e.target.value})}/></label><label>Fecha<input type="date" value={minute.date} onChange={e=>setMinute({...minute,date:e.target.value})}/></label><label>Resumen<textarea placeholder="Resumen de la reunión" value={minute.summary} onChange={e=>setMinute({...minute,summary:e.target.value})}/></label><label>Acuerdos<textarea placeholder="Acuerdos y responsables" value={minute.agreements} onChange={e=>setMinute({...minute,agreements:e.target.value})}/></label><label>Archivo<input type="file" accept="image/*,.pdf,.doc,.docx" onChange={e=>setMinute({...minute,fileName:e.target.files?.[0]?.name||''})}/></label><button className="primary" onClick={()=>{if(!minute.title)return;addMinute(minute);setMinute({title:'',date:'',summary:'',agreements:'',fileName:''})}}>Guardar acta</button></div></Card><Card title="Libro de actas" icon="📚"><div className="dataList">{data.minutes.map(n=><article key={n.id}><div><b>{n.title}</b><span>{n.summary}</span><small>{n.date} · {n.agreements} {n.fileName&&`· ${n.fileName}`}</small></div></article>)}</div></Card></div>}

  {tab==='documents'&&<div className="grid2"><Card title="Agregar documento" icon="📁"><div className="committeeForm labeled"><label>Título<input placeholder="Ejemplo: Padrón de familias" value={document.title} onChange={e=>setDocument({...document,title:e.target.value})}/></label><label>Categoría<select value={document.category} onChange={e=>setDocument({...document,category:e.target.value})}><option>Comprobante</option><option>Padrón</option><option>Presupuesto</option><option>Acta</option><option>Otro</option></select></label><label>Archivo<input type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={e=>setDocument({...document,fileName:e.target.files?.[0]?.name||''})}/></label><label>Descripción<textarea placeholder="Explica qué contiene este documento" value={document.note} onChange={e=>setDocument({...document,note:e.target.value})}/></label><button className="primary" onClick={()=>{if(!document.title)return;addDocument(document);setDocument({title:'',category:'Comprobante',fileName:'',note:''})}}>Guardar referencia</button></div></Card><Card title="Archivo del comité" icon="🗂️"><div className="committeeTable">{data.documents.map(d=><article key={d.id}><div><b>{d.title}</b><small>{d.note}</small></div><span>{d.category}</span><em>{d.fileName||'Sin archivo'}</em><button className="danger" onClick={()=>removeRecord('documents',d.id)}><Trash2 size={14}/></button></article>)}</div></Card></div>}

  {tab==='reports'&&<><div className="committeeKpis"><span><b>{money(summary.collected)}</b><small>Ingresos</small></span><span><b>{money(summary.spent)}</b><small>Gastos</small></span><span><b>{money(summary.balance)}</b><small>Saldo</small></span><span><b>{money(summary.pending)}</b><small>Deuda</small></span></div><div className="grid2"><Card title="Exportar información" icon="📥"><div className="buttonWrap"><button onClick={()=>csv('estado-pagos-comite.csv',[['Alumno','Apoderado',...data.campaigns.map(c=>c.name)],...data.families.map(f=>[f.student,f.guardian,...data.campaigns.map(c=>`${status(f,c)} ${money(paid(f.id,c.id))}`)])])}><Download size={16}/> Estado de pagos CSV</button><button onClick={()=>csv('gastos-comite.csv',[['Fecha','Concepto','Detalle','Responsable','Monto','Comprobante'],...data.expenses.map(e=>[e.date,e.concept,e.detail,e.responsible,e.amount,e.receipt])])}><Download size={16}/> Gastos CSV</button><button onClick={()=>downloadJson(data)}><FileText size={16}/> Respaldo JSON</button><button className="primary" onClick={()=>window.print()}><Printer size={16}/> Imprimir / Guardar PDF</button></div></Card><Card title="Rendición resumida" icon="📊"><p>Total esperado: <b>{money(summary.expected)}</b></p><p>Total cobrado: <b>{money(summary.collected)}</b></p><p>Gastos sustentados: <b>{money(summary.spent)}</b></p><p>Saldo disponible: <b>{money(summary.balance)}</b></p><p>Deuda pendiente: <b>{money(summary.pending)}</b></p></Card></div></>}

  {tab==='settings'&&<div className="grid2"><Card title="Datos del comité" icon="⚙️"><div className="committeeForm labeled"><label>Nombre del comité<input placeholder="Ejemplo: Comité Aula 4 años" value={data.committee.name} onChange={e=>updateCommittee({name:e.target.value})}/><small>Nombre visible para familias y reportes.</small></label><label>Descripción breve<textarea placeholder="Ejemplo: Comité de padres para apoyo en actividades del aula." value={data.committee.description||''} onChange={e=>updateCommittee({description:e.target.value})}/><small>Explica el propósito del comité.</small></label><label>Colegio<input placeholder="Ejemplo: Colegio San Martín" value={data.committee.school} onChange={e=>updateCommittee({school:e.target.value})}/></label><label>Aula o grupo<input placeholder="Ejemplo: Aula 4 años" value={data.committee.classroom} onChange={e=>updateCommittee({classroom:e.target.value})}/></label><label>Año escolar<input placeholder="Ejemplo: 2026" value={data.committee.period} onChange={e=>updateCommittee({period:e.target.value})}/></label><label>Presidenta / presidente<input placeholder="Nombre de la presidenta" value={data.committee.president} onChange={e=>updateCommittee({president:e.target.value})}/></label><label>Tesorera / tesorero<input placeholder="Nombre de la tesorera" value={data.committee.treasurer} onChange={e=>updateCommittee({treasurer:e.target.value})}/></label><label>Secretaría / apoyo<input placeholder="Nombre de apoyo" value={data.committee.secretary} onChange={e=>updateCommittee({secretary:e.target.value})}/></label><label className="checkRow"><input type="checkbox" checked={data.committee.publishEvents} onChange={e=>updateCommittee({publishEvents:e.target.checked})}/> Permitir publicar eventos en MiZona</label></div></Card><Card title="Ayuda y flujo de trabajo" icon="🎥"><div className="workflowList static">{['Participantes: registra familias y marca quién participa.','Cuotas: crea conceptos y montos.','Quién pagó: registra pagos y recordatorios.','Ingresos y gastos: documenta comprobantes.','Comunicados: informa a las familias.','Reportes: descarga CSV o PDF.','Configuración: edita datos y permisos.'].map((text,i)=><div key={text}><b>{i+1}</b><span>{text}</span></div>)}</div><p className="muted">Este orden coincide con las pestañas para que el comité trabaje paso a paso.</p></Card></div>}
 </div>;
}
