import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,Download,FileText,Megaphone,Plus,Printer,ReceiptText,Send,Settings,Trash2,Users,WalletCards} from 'lucide-react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import {useApp} from '../context/AppContext';
import {isStudentProfile} from '../lib/permissions';
import {addAnnouncement,addCampaign,addDocument,addEvent,addExpense,addFamily,addMember,addMinute,addPayment,getCommitteeFinance,markReminder,removeRecord,subscribeCommitteeFinance,toggleCampaign,updateCommittee} from '../lib/localCommittees';
const money=v=>`S/ ${Number(v||0).toFixed(2)}`;
const csv=(name,rows)=>{const text=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const downloadJson=data=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='respaldo-comite-mizona.json';a.click();URL.revokeObjectURL(a.href)};
export default function Committees({setPage}){
 const {profile}=useApp(); const [data,setData]=useState(getCommitteeFinance); const [tab,setTab]=useState('dashboard'); const [notice,setNotice]=useState('');
 useEffect(()=>subscribeCommitteeFinance(setData),[]);
 const [campaign,setCampaign]=useState({name:'',category:'',amount:'',dueDate:'',description:''});
 const [payment,setPayment]=useState({familyId:'',campaignId:'',amount:'',method:'Yape',reference:'',receiptName:''});
 const [expense,setExpense]=useState({campaignId:'',concept:'',detail:'',amount:'',responsible:'',receipt:'',receiptName:''});
 const [family,setFamily]=useState({student:'',guardian:'',phone:''});
 const [announcement,setAnnouncement]=useState({title:'',body:'',audience:'Familias del aula',published:true});
 const [event,setEvent]=useState({title:'',date:'',time:'',place:'',description:'',publishHome:true});
 const [minute,setMinute]=useState({title:'',date:'',summary:'',agreements:'',fileName:''});
 const [document,setDocument]=useState({title:'',category:'Comprobante',fileName:'',note:''});
 const [member,setMember]=useState({name:'',role:'Vocal',phone:''});
 const summary=useMemo(()=>{const expected=data.campaigns.reduce((s,c)=>s+Number(c.amount)*data.families.length,0);const collected=data.payments.reduce((s,p)=>s+Number(p.amount),0);const spent=data.expenses.reduce((s,e)=>s+Number(e.amount),0);return{expected,collected,spent,balance:collected-spent,pending:Math.max(0,expected-collected),families:data.families.length,activities:data.campaigns.filter(c=>c.status==='active').length}},[data]);
 const paid=(f,c)=>data.payments.filter(p=>p.familyId===f&&p.campaignId===c).reduce((s,p)=>s+Number(p.amount),0);
 const status=(f,c)=>{const x=paid(f.id,c.id);return x>=Number(c.amount)?'Pagado':x>0?'Parcial':'Pendiente'};
 if(isStudentProfile(profile))return <div className="page"><Card title="Acceso protegido" icon="🛡️"><p>La administración del comité solo está disponible para adultos responsables.</p><button className="primary" onClick={()=>setPage('campus')}>Volver</button></Card></div>;
 const notify=(f,c)=>{markReminder(f.id,c.id);setNotice(`Recordatorio preparado para ${f.guardian}: ${c.name} · ${money(Number(c.amount)-paid(f.id,c.id))} pendiente.`)};
 const tabs=[['dashboard','Inicio','📊'],['campaigns','Cuotas','🧾'],['matrix','Quién pagó','✅'],['payments','Ingresos','💳'],['expenses','Gastos','💸'],['announcements','Comunicados','📣'],['events','Eventos','📅'],['minutes','Actas','📝'],['documents','Documentos','📁'],['families','Miembros','👥'],['reports','Reportes','📈'],['settings','Configuración','⚙️']].map(([id,label,icon])=>({id,label,icon}));
 return <div className="page committeeFinancePage">
  <section className="committeeHero"><div><p className="eyebrow">Comité completo y transparente</p><h1>{data.committee.name}</h1><p>{data.committee.school} · {data.committee.classroom} · Periodo {data.committee.period}. Controla cuotas, gastos, acuerdos, eventos y documentos en un solo lugar.</p></div><div className="committeeHeroStats"><span><b>{money(summary.collected)}</b>Cobrado</span><span><b>{money(summary.pending)}</b>Pendiente</span><span><b>{money(summary.balance)}</b>Saldo</span></div></section>
  {notice&&<div className="localModeStrip"><Send size={18}/><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
  <Tabs active={tab} setActive={setTab} tabs={tabs}/>
  {tab==='dashboard'&&<><div className="committeeKpis"><span><b>{money(summary.expected)}</b><small>Total esperado</small></span><span><b>{money(summary.collected)}</b><small>Total cobrado</small></span><span><b>{money(summary.spent)}</b><small>Gastos</small></span><span><b>{money(summary.balance)}</b><small>Saldo real</small></span></div><div className="grid2"><Card title="Próximas actividades" icon="📌"><div className="dataList">{data.campaigns.filter(c=>c.status==='active').map(c=><article key={c.id}><div><b>{c.name}</b><span>{c.category} · vence {c.dueDate}</span></div><strong>{money(c.amount)}</strong></article>)}</div></Card><Card title="Últimos comunicados y eventos" icon="📣"><div className="dataList">{data.announcements.slice(0,2).map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.body}</span></div></article>)}{data.events.slice(0,2).map(e=><article key={e.id}><div><b>{e.title}</b><span>{e.date} {e.time} · {e.place}</span></div></article>)}</div></Card></div><div className="grid2"><Card title="Acciones rápidas" icon="⚙️"><div className="buttonWrap"><button className="primary" onClick={()=>setTab('payments')}><Plus size={16}/> Registrar pago</button><button onClick={()=>setTab('campaigns')}><ReceiptText size={16}/> Nueva cuota</button><button onClick={()=>setTab('announcements')}><Megaphone size={16}/> Comunicado</button><button onClick={()=>setTab('events')}><CalendarDays size={16}/> Evento</button></div></Card><Card title="Transparencia" icon="🔎"><p><b>{summary.families}</b> familias registradas, <b>{summary.activities}</b> actividades abiertas y <b>{data.expenses.length}</b> gastos documentados.</p><button onClick={()=>setTab('reports')}><Download size={16}/> Ver rendición de cuentas</button></Card></div></>}
  {tab==='campaigns'&&<div className="grid2"><Card title="Crear cuota o actividad" icon="➕"><div className="committeeForm"><input placeholder="Nombre" value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/><input placeholder="Categoría" value={campaign.category} onChange={e=>setCampaign({...campaign,category:e.target.value})}/><input type="number" placeholder="Monto por familia" value={campaign.amount} onChange={e=>setCampaign({...campaign,amount:e.target.value})}/><input type="date" value={campaign.dueDate} onChange={e=>setCampaign({...campaign,dueDate:e.target.value})}/><textarea placeholder="Objetivo y detalle" value={campaign.description} onChange={e=>setCampaign({...campaign,description:e.target.value})}/><button className="primary" onClick={()=>{if(!campaign.name||!campaign.amount)return;addCampaign({...campaign,amount:Number(campaign.amount)});setCampaign({name:'',category:'',amount:'',dueDate:'',description:''})}}>Guardar</button></div></Card><Card title="Cuotas registradas" icon="🧾"><div className="committeeTable compact">{data.campaigns.map(c=><article key={c.id}><div><b>{c.name}</b><small>{c.description}</small></div><span>{money(c.amount)}</span><em>{c.dueDate}</em><button onClick={()=>toggleCampaign(c.id)}>{c.status==='active'?'Cerrar':'Reabrir'}</button></article>)}</div></Card></div>}
  {tab==='matrix'&&<Card title="Control por alumno y concepto" icon="✅"><div className="paymentMatrix"><table><thead><tr><th>Alumno / apoderado</th>{data.campaigns.map(c=><th key={c.id}>{c.name}<small>{money(c.amount)}</small></th>)}</tr></thead><tbody>{data.families.map(f=><tr key={f.id}><td><b>{f.student}</b><small>{f.guardian}<br/>{f.phone}</small></td>{data.campaigns.map(c=>{const st=status(f,c);return <td key={c.id}><span className={`matrixStatus ${st.toLowerCase()}`}>{st}</span><small>{money(paid(f.id,c.id))} / {money(c.amount)}</small>{st!=='Pagado'&&<button onClick={()=>notify(f,c)}><Send size={14}/> Recordar</button>}</td>})}</tr>)}</tbody></table></div></Card>}
  {tab==='payments'&&<div className="grid2"><Card title="Registrar ingreso" icon="💳"><div className="committeeForm"><select value={payment.familyId} onChange={e=>setPayment({...payment,familyId:e.target.value})}><option value="">Alumno</option>{data.families.map(f=><option key={f.id} value={f.id}>{f.student} · {f.guardian}</option>)}</select><select value={payment.campaignId} onChange={e=>{const c=data.campaigns.find(x=>x.id===e.target.value);setPayment({...payment,campaignId:e.target.value,amount:c?String(c.amount):payment.amount})}}><option value="">Concepto</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="number" placeholder="Monto" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>Yape</option><option>Plin</option><option>Efectivo</option><option>Transferencia</option></select><input placeholder="Operación o recibo" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/><input type="file" accept="image/*,.pdf" onChange={e=>setPayment({...payment,receiptName:e.target.files?.[0]?.name||''})}/><button className="primary" onClick={()=>{if(!payment.familyId||!payment.campaignId||!payment.amount)return;addPayment({...payment,amount:Number(payment.amount)});setPayment({familyId:'',campaignId:'',amount:'',method:'Yape',reference:'',receiptName:''});setNotice('Pago registrado correctamente.')}}><WalletCards size={16}/> Guardar pago</button></div></Card><Card title="Historial de ingresos" icon="📋"><div className="committeeTable compact">{data.payments.map(p=>{const f=data.families.find(x=>x.id===p.familyId),c=data.campaigns.find(x=>x.id===p.campaignId);return <article key={p.id}><div><b>{f?.student||'Alumno'}</b><small>{c?.name}</small></div><span>{money(p.amount)}</span><em>{p.method} · {p.date}</em><small>{p.reference} {p.receiptName&&`· ${p.receiptName}`}</small></article>})}</div></Card></div>}
  {tab==='expenses'&&<div className="grid2"><Card title="Registrar gasto detallado" icon="💸"><div className="committeeForm"><select value={expense.campaignId} onChange={e=>setExpense({...expense,campaignId:e.target.value})}><option value="">Fondo o actividad</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Concepto" value={expense.concept} onChange={e=>setExpense({...expense,concept:e.target.value})}/><textarea placeholder="Explicación del gasto" value={expense.detail} onChange={e=>setExpense({...expense,detail:e.target.value})}/><input type="number" placeholder="Monto" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/><input placeholder="Responsable" value={expense.responsible} onChange={e=>setExpense({...expense,responsible:e.target.value})}/><input placeholder="Boleta, factura o recibo" value={expense.receipt} onChange={e=>setExpense({...expense,receipt:e.target.value})}/><input type="file" accept="image/*,.pdf" onChange={e=>setExpense({...expense,receiptName:e.target.files?.[0]?.name||''})}/><button className="primary" onClick={()=>{if(!expense.concept||!expense.amount)return;addExpense({...expense,amount:Number(expense.amount)});setExpense({campaignId:'',concept:'',detail:'',amount:'',responsible:'',receipt:'',receiptName:''})}}>Guardar gasto</button></div></Card><Card title="Gastos y comprobantes" icon="🧾"><div className="committeeTable">{data.expenses.map(e=><article key={e.id}><div><b>{e.concept}</b><small>{e.detail}</small></div><span>{money(e.amount)}</span><em>{e.date} · {e.responsible}</em><small>{e.receipt} {e.receiptName&&`· ${e.receiptName}`}</small></article>)}</div></Card></div>}
  {tab==='announcements'&&<div className="grid2"><Card title="Nuevo comunicado" icon="📣"><div className="committeeForm"><input placeholder="Título" value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/><textarea placeholder="Mensaje para las familias" value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/><input placeholder="Destinatarios" value={announcement.audience} onChange={e=>setAnnouncement({...announcement,audience:e.target.value})}/><label><input type="checkbox" checked={announcement.published} onChange={e=>setAnnouncement({...announcement,published:e.target.checked})}/> Publicar ahora</label><button className="primary" onClick={()=>{if(!announcement.title||!announcement.body)return;addAnnouncement(announcement);setAnnouncement({title:'',body:'',audience:'Familias del aula',published:true})}}>Publicar comunicado</button></div></Card><Card title="Comunicados" icon="📨"><div className="dataList">{data.announcements.map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.body}</span><small>{a.audience} · {a.published?'Publicado':'Borrador'}</small></div></article>)}</div></Card></div>}
  {tab==='events'&&<div className="grid2"><Card title="Crear evento" icon="📅"><div className="committeeForm"><input placeholder="Evento" value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/><input type="date" value={event.date} onChange={e=>setEvent({...event,date:e.target.value})}/><input type="time" value={event.time} onChange={e=>setEvent({...event,time:e.target.value})}/><input placeholder="Lugar" value={event.place} onChange={e=>setEvent({...event,place:e.target.value})}/><textarea placeholder="Descripción" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/><label><input type="checkbox" checked={event.publishHome} onChange={e=>setEvent({...event,publishHome:e.target.checked})}/> Mostrar en la página principal de MiZona</label><button className="primary" onClick={()=>{if(!event.title||!event.date)return;addEvent(event);setEvent({title:'',date:'',time:'',place:'',description:'',publishHome:true})}}>Guardar evento</button></div></Card><Card title="Calendario del comité" icon="🗓️"><div className="dataList">{data.events.map(e=><article key={e.id}><div><b>{e.title}</b><span>{e.date} {e.time} · {e.place}</span><small>{e.description} {e.publishHome&&'· Visible en MiZona'}</small></div></article>)}</div></Card></div>}
  {tab==='minutes'&&<div className="grid2"><Card title="Registrar acta o acuerdo" icon="📝"><div className="committeeForm"><input placeholder="Título del acta" value={minute.title} onChange={e=>setMinute({...minute,title:e.target.value})}/><input type="date" value={minute.date} onChange={e=>setMinute({...minute,date:e.target.value})}/><textarea placeholder="Resumen de la reunión" value={minute.summary} onChange={e=>setMinute({...minute,summary:e.target.value})}/><textarea placeholder="Acuerdos y responsables" value={minute.agreements} onChange={e=>setMinute({...minute,agreements:e.target.value})}/><input type="file" accept="image/*,.pdf,.doc,.docx" onChange={e=>setMinute({...minute,fileName:e.target.files?.[0]?.name||''})}/><button className="primary" onClick={()=>{if(!minute.title)return;addMinute(minute);setMinute({title:'',date:'',summary:'',agreements:'',fileName:''})}}>Guardar acta</button></div></Card><Card title="Libro de actas" icon="📚"><div className="dataList">{data.minutes.map(n=><article key={n.id}><div><b>{n.title}</b><span>{n.summary}</span><small>{n.date} · {n.agreements} {n.fileName&&`· ${n.fileName}`}</small></div></article>)}</div></Card></div>}
  {tab==='documents'&&<div className="grid2"><Card title="Agregar documento" icon="📁"><div className="committeeForm"><input placeholder="Título" value={document.title} onChange={e=>setDocument({...document,title:e.target.value})}/><select value={document.category} onChange={e=>setDocument({...document,category:e.target.value})}><option>Comprobante</option><option>Padrón</option><option>Presupuesto</option><option>Acta</option><option>Otro</option></select><input type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={e=>setDocument({...document,fileName:e.target.files?.[0]?.name||''})}/><textarea placeholder="Descripción" value={document.note} onChange={e=>setDocument({...document,note:e.target.value})}/><button className="primary" onClick={()=>{if(!document.title)return;addDocument(document);setDocument({title:'',category:'Comprobante',fileName:'',note:''})}}>Guardar referencia</button></div></Card><Card title="Archivo del comité" icon="🗂️"><div className="committeeTable">{data.documents.map(d=><article key={d.id}><div><b>{d.title}</b><small>{d.note}</small></div><span>{d.category}</span><em>{d.fileName||'Sin archivo'}</em><button className="danger" onClick={()=>removeRecord('documents',d.id)}><Trash2 size={14}/></button></article>)}</div></Card></div>}
  {tab==='families'&&<><div className="grid2"><Card title="Agregar alumno y apoderado" icon="👨‍👩‍👧"><div className="committeeForm"><input placeholder="Alumno" value={family.student} onChange={e=>setFamily({...family,student:e.target.value})}/><input placeholder="Apoderado" value={family.guardian} onChange={e=>setFamily({...family,guardian:e.target.value})}/><input placeholder="Teléfono" value={family.phone} onChange={e=>setFamily({...family,phone:e.target.value})}/><button className="primary" onClick={()=>{if(!family.student)return;addFamily(family);setFamily({student:'',guardian:'',phone:''})}}><Users size={16}/> Agregar familia</button></div></Card><Card title="Agregar integrante del comité" icon="🪪"><div className="committeeForm"><input placeholder="Nombre" value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/><select value={member.role} onChange={e=>setMember({...member,role:e.target.value})}><option>Presidenta</option><option>Tesorera</option><option>Secretario</option><option>Vocal</option><option>Delegado</option></select><input placeholder="Teléfono" value={member.phone} onChange={e=>setMember({...member,phone:e.target.value})}/><button onClick={()=>{if(!member.name)return;addMember(member);setMember({name:'',role:'Vocal',phone:''})}}>Agregar cargo</button></div></Card></div><div className="grid2"><Card title="Familias del aula" icon="📋"><div className="committeeTable compact">{data.families.map(f=><article key={f.id}><b>{f.student}</b><span>{f.guardian}</span><span>{f.phone}</span></article>)}</div></Card><Card title="Junta directiva" icon="🏛️"><div className="committeeTable compact">{data.members.map(m=><article key={m.id}><b>{m.name}</b><span>{m.role}</span><span>{m.phone}</span></article>)}</div></Card></div></>}
  {tab==='reports'&&<><div className="committeeKpis"><span><b>{money(summary.collected)}</b><small>Ingresos</small></span><span><b>{money(summary.spent)}</b><small>Gastos</small></span><span><b>{money(summary.balance)}</b><small>Saldo</small></span><span><b>{money(summary.pending)}</b><small>Deuda</small></span></div><div className="grid2"><Card title="Exportar información" icon="📥"><div className="buttonWrap"><button onClick={()=>csv('estado-pagos-comite.csv',[['Alumno','Apoderado',...data.campaigns.map(c=>c.name)],...data.families.map(f=>[f.student,f.guardian,...data.campaigns.map(c=>`${status(f,c)} ${money(paid(f.id,c.id))}`)])])}><Download size={16}/> Estado de pagos CSV</button><button onClick={()=>csv('gastos-comite.csv',[['Fecha','Concepto','Detalle','Responsable','Monto','Comprobante'],...data.expenses.map(e=>[e.date,e.concept,e.detail,e.responsible,e.amount,e.receipt])])}><Download size={16}/> Gastos CSV</button><button onClick={()=>downloadJson(data)}><FileText size={16}/> Respaldo JSON</button><button className="primary" onClick={()=>window.print()}><Printer size={16}/> Imprimir / Guardar PDF</button></div></Card><Card title="Rendición resumida" icon="📊"><p>Total esperado: <b>{money(summary.expected)}</b></p><p>Total cobrado: <b>{money(summary.collected)}</b></p><p>Gastos sustentados: <b>{money(summary.spent)}</b></p><p>Saldo disponible: <b>{money(summary.balance)}</b></p><p>Deuda pendiente: <b>{money(summary.pending)}</b></p></Card></div></>}
  {tab==='settings'&&<div className="grid2"><Card title="Datos del comité" icon="⚙️"><div className="committeeForm"><input value={data.committee.name} onChange={e=>updateCommittee({name:e.target.value})}/><input value={data.committee.school} onChange={e=>updateCommittee({school:e.target.value})}/><input value={data.committee.classroom} onChange={e=>updateCommittee({classroom:e.target.value})}/><input value={data.committee.period} onChange={e=>updateCommittee({period:e.target.value})}/><input placeholder="Presidenta/e" value={data.committee.president} onChange={e=>updateCommittee({president:e.target.value})}/><input placeholder="Tesorera/o" value={data.committee.treasurer} onChange={e=>updateCommittee({treasurer:e.target.value})}/><input placeholder="Secretaria/o" value={data.committee.secretary} onChange={e=>updateCommittee({secretary:e.target.value})}/><label><input type="checkbox" checked={data.committee.publishEvents} onChange={e=>updateCommittee({publishEvents:e.target.checked})}/> Permitir publicar eventos en MiZona</label></div></Card><Card title="Ayuda y transparencia" icon="🎥"><p>Guía rápida:</p><ol><li>Registra familias.</li><li>Crea cuotas o actividades.</li><li>Registra pagos y comprobantes.</li><li>Documenta cada gasto.</li><li>Publica comunicados y eventos.</li><li>Descarga la rendición en CSV o PDF.</li></ol><p className="muted">El video introductorio queda preparado para conectarse cuando tengas el archivo o enlace definitivo.</p></Card></div>}
 </div>
}
