import {useEffect,useMemo,useState} from 'react';
import {Landmark,Webhook,WalletCards,RefreshCcw,Download,ShieldCheck} from 'lucide-react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import {useApp} from '../context/AppContext';
import {isPlatformAdmin} from '../lib/permissions';
import {createRefund,createSettlement,exportGateway,getGatewayState,setActiveProvider,simulateWebhook,subscribeGateway,updateGatewaySettings,updateProvider,updateRefund,updateSettlement} from '../lib/localGateway';
const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(n||0));
export default function GatewayCenter(){
 const {profile}=useApp(); const admin=isPlatformAdmin(profile); const [state,setState]=useState(getGatewayState); const [tab,setTab]=useState('providers'); const [msg,setMsg]=useState('');
 useEffect(()=>subscribeGateway(setState),[]);
 const summary=useMemo(()=>({held:state.settlements.filter(x=>x.status==='held').reduce((a,x)=>a+x.net,0),available:state.settlements.filter(x=>x.status==='available').reduce((a,x)=>a+x.net,0),events:state.events.length,refunds:state.refunds.length}),[state]);
 if(!admin)return <Card title="Acceso restringido" icon="🔒"><p>Solo el administrador puede configurar pasarelas, liquidaciones y devoluciones.</p></Card>;
 const save=e=>{e.preventDefault();const f=new FormData(e.currentTarget);setState(updateGatewaySettings({environment:f.get('environment'),currency:f.get('currency'),settlement_days:Number(f.get('settlement_days')),reserve_percent:Number(f.get('reserve_percent')),min_payout:Number(f.get('min_payout')),require_3ds:f.get('require_3ds')==='on',auto_capture:f.get('auto_capture')==='on',allow_refunds:f.get('allow_refunds')==='on'}));setMsg('Configuración guardada.');};
 return <div className="pageStack gatewayPage"><section className="pageHero"><div><span className="eyebrow">Etapa 26</span><h1>Pasarela y liquidaciones</h1><p>Centro local para preparar proveedores, webhooks, saldos de vendedores y devoluciones.</p></div><div className="heroBadge"><ShieldCheck size={18}/> Sandbox seguro</div></section>
 {msg&&<div className="inlineNotice">{msg}</div>}
 <div className="metricGrid"><Card title="Disponible" value={money(summary.available)} icon="💰"/><Card title="Retenido" value={money(summary.held)} icon="🛡️"/><Card title="Eventos" value={summary.events} icon="🔔"/><Card title="Devoluciones" value={summary.refunds} icon="↩️"/></div>
 <Tabs value={tab} onChange={setTab} items={[['providers','Proveedores'],['settlements','Liquidaciones'],['webhooks','Webhooks'],['refunds','Devoluciones'],['settings','Configuración']]}/>
 {tab==='providers'&&<Card title="Proveedores preparados" icon={<Landmark size={18}/>}><div className="gatewayGrid">{state.providers.map(p=><article className="gatewayCard" key={p.id}><div><b>{p.name}</b><span>{p.mode==='sandbox'?'Modo prueba':'Producción'}</span></div><label><input type="checkbox" checked={p.enabled} onChange={e=>setState(updateProvider(p.id,{enabled:e.target.checked}))}/> Activo</label><label><input type="checkbox" checked={p.configured} onChange={e=>setState(updateProvider(p.id,{configured:e.target.checked}))}/> Configurado</label><small>{p.supports_split?'Permite pago dividido':'Sin división automática confirmada'}</small><button disabled={!p.enabled||!p.configured||state.settings.active_provider===p.id} onClick={()=>{try{setState(setActiveProvider(p.id));setMsg(`${p.name} quedó como proveedor activo.`)}catch(e){setMsg(e.message)}}}>{state.settings.active_provider===p.id?'Proveedor actual':'Usar proveedor'}</button></article>)}</div></Card>}
 {tab==='settlements'&&<><Card title="Crear liquidación de prueba" icon={<WalletCards size={18}/>}><form className="inlineForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setState(createSettlement(f.get('seller'),f.get('gross')));e.currentTarget.reset()}}><input name="seller" placeholder="Vendedor" required/><input name="gross" type="number" min="1" step="0.01" placeholder="Monto bruto" required/><button>Crear liquidación</button></form></Card><Card title="Saldos de vendedores" icon="📊"><div className="dataList">{state.settlements.map(x=><article key={x.id}><div><b>{x.seller}</b><span>{x.id} · {x.status}</span></div><div><strong>{money(x.net)}</strong><small>Bruto {money(x.gross)} · Comisión {money(x.commission)} · Reserva {money(x.reserve)}</small></div><div className="rowActions">{x.status==='held'&&<button onClick={()=>setState(updateSettlement(x.id,'available'))}>Liberar</button>}{x.status==='available'&&<button onClick={()=>setState(updateSettlement(x.id,'paid'))}>Marcar pagado</button>}<button className="ghostButton" onClick={()=>setState(updateSettlement(x.id,'blocked'))}>Bloquear</button></div></article>)}</div></Card></>}
 {tab==='webhooks'&&<><Card title="Simular webhook" icon={<Webhook size={18}/>}><div className="buttonWrap">{['payment.approved','payment.failed','payment.held','payment.refunded'].map(t=><button key={t} onClick={()=>setState(simulateWebhook(t))}>{t}</button>)}</div></Card><Card title="Eventos recibidos" icon="📡"><div className="dataList">{state.events.map(e=><article key={e.id}><div><b>{e.type}</b><span>{e.reference}</span></div><div><strong>{e.provider}</strong><small>{new Date(e.created_at).toLocaleString('es-PE')}</small></div></article>)}</div></Card></>}
 {tab==='refunds'&&<><Card title="Solicitar devolución" icon={<RefreshCcw size={18}/>}><form className="inlineForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setState(createRefund(f.get('reference'),f.get('amount'),f.get('reason')));e.currentTarget.reset()}}><input name="reference" placeholder="Referencia PAY-..." required/><input name="amount" type="number" step="0.01" min="1" placeholder="Monto" required/><input name="reason" placeholder="Motivo" required/><button>Registrar</button></form></Card><Card title="Casos de devolución" icon="↩️"><div className="dataList">{state.refunds.length===0?<p>No hay devoluciones.</p>:state.refunds.map(r=><article key={r.id}><div><b>{r.reference}</b><span>{r.reason}</span></div><div><strong>{money(r.amount)}</strong><small>{r.status}</small></div><div className="rowActions">{r.status==='requested'&&<button onClick={()=>setState(updateRefund(r.id,'approved'))}>Aprobar</button>}{r.status==='approved'&&<button onClick={()=>setState(updateRefund(r.id,'completed'))}>Completar</button>}<button className="ghostButton" onClick={()=>setState(updateRefund(r.id,'rejected'))}>Rechazar</button></div></article>)}</div></Card></>}
 {tab==='settings'&&<Card title="Configuración general" icon="⚙️"><form className="paymentForm" onSubmit={save}><label>Entorno<select name="environment" defaultValue={state.settings.environment}><option value="sandbox">Sandbox</option><option value="production">Producción bloqueada</option></select></label><label>Moneda<input name="currency" defaultValue={state.settings.currency}/></label><label>Días para liquidar<input name="settlement_days" type="number" min="0" defaultValue={state.settings.settlement_days}/></label><label>Reserva antifraude (%)<input name="reserve_percent" type="number" min="0" max="100" step="0.1" defaultValue={state.settings.reserve_percent}/></label><label>Retiro mínimo<input name="min_payout" type="number" min="0" defaultValue={state.settings.min_payout}/></label><label className="checkLabel"><input name="require_3ds" type="checkbox" defaultChecked={state.settings.require_3ds}/> Exigir autenticación reforzada</label><label className="checkLabel"><input name="auto_capture" type="checkbox" defaultChecked={state.settings.auto_capture}/> Captura automática</label><label className="checkLabel"><input name="allow_refunds" type="checkbox" defaultChecked={state.settings.allow_refunds}/> Permitir devoluciones</label><button>Guardar</button></form><div className="warningBox"><b>No coloques claves secretas aquí.</b><span>Las credenciales reales deben permanecer en funciones de servidor o backend.</span></div><button className="secondaryButton" onClick={exportGateway}><Download size={16}/> Descargar configuración</button></Card>}
 </div>
}
