import { useEffect, useMemo, useState } from 'react';
import {
  BadgeCheck, ChevronRight, Clock3, Flag, Heart, MapPin, MessageCircle,
  PackageCheck, Search, ShieldCheck, ShoppingBag, Sparkles, UserRound, X
} from 'lucide-react';
import Card from '../components/Card';
import { useApp } from '../context/AppContext';
import { sendLocalContactRequest, startLocalDirectConversation } from '../lib/localStore';
import {
  createLocalListing, getLocalCommerceSnapshot, registerLocalListingContact,
  registerLocalListingView, reportLocalListing, subscribeLocalCommerce,
  toggleLocalListingFavorite, updateLocalListingStatus
} from '../lib/localCommerce';

const categories=[
  {id:'all',label:'Todo',icon:'✨'}, {id:'home',label:'Hogar',icon:'🏠'},
  {id:'tech',label:'Tecnología',icon:'📱'}, {id:'school',label:'Escolar',icon:'🎒'},
  {id:'fashion',label:'Ropa',icon:'👕'}, {id:'kids',label:'Niños',icon:'🧸'},
  {id:'services',label:'Servicios',icon:'🛠️'}
];
const categoryEmoji={home:'🏠',tech:'📱',school:'🎒',fashion:'👕',kids:'🧸',services:'🧰'};
const emptyForm={title:'',category:'home',price:'',condition:'Nuevo',zone:'Pachacútec',description:'',delivery:false,negotiable:false,image_data:null,image:'📦'};
function distanceLabel(value){return Number(value)<1?`${Math.round(Number(value)*1000)} m`:`${Number(value).toFixed(1)} km`;}
function timeLabel(value){const ms=Date.now()-new Date(value).getTime();if(ms<3600000)return `Hace ${Math.max(1,Math.round(ms/60000))} min`;if(ms<86400000)return `Hace ${Math.round(ms/3600000)} h`;return `Hace ${Math.round(ms/86400000)} días`;}

function ListingCard({item,onOpen,onFavorite,favorite}){
  return <article className={`marketCard ${item.status!=='active'?'commerceInactive':''}`}>
    <div className="marketVisual">{item.image_data?<img src={item.image_data} alt=""/>:<span>{item.image}</span>}<b>{item.condition}</b>{item.is_mine&&<i className="mineBadge">Tu publicación</i>}</div>
    <div className="marketBody">{item.status!=='active'&&<span className={`publicationState ${item.status}`}>{item.status==='pending'?'Pendiente de revisión':item.status==='sold'?'Vendido':item.status}</span>}<div className="marketTitle"><div><h3>{item.title}</h3><strong>S/ {Number(item.price).toFixed(2)}</strong></div><button className={`heartBtn ${favorite?'saved':''}`} onClick={()=>onFavorite(item.id)}><Heart size={18} fill={favorite?'currentColor':'none'}/></button></div><div className="sellerLine"><UserRound size={15}/><b>@{item.seller_username}</b>{item.verified&&<BadgeCheck size={16}/>}</div><div className="marketMeta"><span><MapPin size={14}/>{item.zone} · {distanceLabel(item.distance_km)}</span><span><Clock3 size={14}/>{timeLabel(item.created_at)}</span></div><div className="placeBadges">{(item.tags||[]).map(tag=><span key={tag}>{tag}</span>)}</div><div className="placeActions"><button className="secondary" onClick={()=>onOpen(item)}>Ver detalle</button><button className="primary" onClick={()=>onOpen(item)}>Contactar <ChevronRight size={16}/></button></div></div>
  </article>;
}

export default function Marketplace({ setPage }){
  const { profile }=useApp();
  const [snapshot,setSnapshot]=useState(getLocalCommerceSnapshot);
  const [category,setCategory]=useState('all'); const [query,setQuery]=useState('');
  const [condition,setCondition]=useState('all'); const [sort,setSort]=useState('recent');
  const [onlyVerified,setOnlyVerified]=useState(false); const [showOnlyMine,setShowOnlyMine]=useState(false);
  const [selected,setSelected]=useState(null); const [showPublish,setShowPublish]=useState(false);
  const [form,setForm]=useState(emptyForm); const [toast,setToast]=useState(''); const [error,setError]=useState('');
  useEffect(()=>subscribeLocalCommerce(setSnapshot),[]);
  const favoriteSet=useMemo(()=>new Set(snapshot.myListingFavoriteIds),[snapshot.myListingFavoriteIds]);
  const listings=useMemo(()=>{
    let list=snapshot.listings.filter(x=>category==='all'||x.category===category).filter(x=>condition==='all'||x.condition.toLowerCase().includes(condition)).filter(x=>!onlyVerified||x.verified).filter(x=>!showOnlyMine||x.seller_id===profile.id).filter(x=>`${x.title} ${x.description} ${x.seller_username} ${x.zone}`.toLowerCase().includes(query.toLowerCase()));
    return [...list].sort((a,b)=>sort==='priceLow'?a.price-b.price:sort==='priceHigh'?b.price-a.price:sort==='distance'?a.distance_km-b.distance_km:new Date(b.created_at)-new Date(a.created_at));
  },[snapshot.listings,category,query,condition,sort,onlyVerified,showOnlyMine,profile.id]);
  const myListings=snapshot.listings.filter(x=>x.seller_id===profile.id);
  const notify=t=>{setToast(t);setError('');setTimeout(()=>setToast(''),2500);}; const fail=e=>{setError(e?.message||String(e));setTimeout(()=>setError(''),4200);};
  const openListing=item=>{registerLocalListingView(item.id);setSelected({...item,views:Number(item.views||0)+1});};
  const publish=()=>{try{createLocalListing({...form,image:form.image||categoryEmoji[form.category]||'📦'});setShowPublish(false);setForm(emptyForm);notify('Publicación enviada a revisión local.');}catch(e){fail(e);}};
  const contactSeller=item=>{try{if(item.seller_id===profile.id)throw new Error('Esta publicación es tuya.');try{startLocalDirectConversation(item.seller_id);registerLocalListingContact(item.id);setSelected(null);setPage?.('chat');}catch(chatError){if(String(chatError.message).includes('contactos')){sendLocalContactRequest(item.seller_username);notify('Enviamos una solicitud de contacto al vendedor.');}else throw chatError;}}catch(e){fail(e);}};
  const chooseImage=event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>1200000){fail('La imagen local debe pesar menos de 1.2 MB.');event.target.value='';return;}const reader=new FileReader();reader.onload=()=>setForm(current=>({...current,image_data:String(reader.result),image:'🖼️'}));reader.onerror=()=>fail('No se pudo leer la imagen.');reader.readAsDataURL(file);};
  const setStatus=(id,status)=>{try{updateLocalListingStatus(id,status);setSelected(null);notify(status==='sold'?'Publicación marcada como vendida.':`Estado actualizado: ${status}.`);}catch(e){fail(e);}};

  return <div className="page marketplacePage commerceV17">
    <section className="marketHero"><div><p className="eyebrow">Marketplace multiusuario local</p><h1>Compra y vende dentro de tu zona</h1><p>Publica productos o servicios, usa favoritos independientes y coordina mediante MiZona Chat.</p><div className="heroActions"><button className="primary" onClick={()=>setShowPublish(true)}><ShoppingBag size={17}/> Publicar producto</button><button className="secondary" onClick={()=>setShowOnlyMine(v=>!v)}><PackageCheck size={17}/> {showOnlyMine?'Ver todo':`Mis publicaciones (${myListings.length})`}</button></div></div><div className="marketHeroStats"><span><b>{snapshot.listings.filter(x=>x.status==='active').length}</b> activas</span><span><b>{snapshot.listings.filter(x=>x.verified).length}</b> verificadas</span><span><b>{snapshot.pendingListingCount}</b> pendientes</span></div></section>

    <section className="marketControls"><div className="businessSearch"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca mochila, tablet, bicicleta, libros..."/></div><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="all">Todas las condiciones</option><option value="nuevo">Nuevo</option><option value="usado">Usado</option><option value="servicio">Servicio</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Más recientes</option><option value="priceLow">Menor precio</option><option value="priceHigh">Mayor precio</option><option value="distance">Más cercanos</option></select><label><input type="checkbox" checked={onlyVerified} onChange={e=>setOnlyVerified(e.target.checked)}/> Verificados</label></section>
    <div className="categoryRail">{categories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}><span>{c.icon}</span>{c.label}</button>)}</div>

    <div className="marketLayout"><section><div className="sectionTitle"><h2>{listings.length} publicaciones</h2><p>Los cambios se reflejan automáticamente en otras pestañas de este navegador.</p></div><div className="marketGrid">{listings.map(item=><ListingCard key={item.id} item={item} onOpen={openListing} onFavorite={id=>toggleLocalListingFavorite(id)} favorite={favoriteSet.has(item.id)}/>)}</div>{!listings.length&&<div className="emptyState">No encontramos publicaciones con esos filtros.</div>}</section><aside className="marketSide"><Card title="Tus publicaciones" icon="📦"><div className="commerceMiniList">{myListings.length?myListings.slice(0,6).map(item=><button key={item.id} onClick={()=>openListing(item)}><span>{item.image_data?'🖼️':item.image}</span><div><b>{item.title}</b><small>{item.status} · S/ {Number(item.price).toFixed(2)}</small></div></button>):<p className="muted">Todavía no has publicado.</p>}</div><button className="primary full" onClick={()=>setShowPublish(true)}>Crear publicación</button></Card><Card title="Compra con seguridad" icon="🛡️"><ul className="list compact"><li>No envíes dinero sin verificar el producto.</li><li>Coordina en lugares públicos y concurridos.</li><li>No compartas claves ni códigos.</li><li>Reporta publicaciones sospechosas.</li></ul></Card></aside></div>

    {selected&&<div className="modalBackdrop" onMouseDown={()=>setSelected(null)}><section className="marketModal commerceDetailModal" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setSelected(null)}><X size={18}/></button><div className="marketModalTop"><div className="marketDetailImage">{selected.image_data?<img src={selected.image_data} alt=""/>:<span>{selected.image}</span>}</div><div><p className="eyebrow">{selected.condition}</p><h2>{selected.title}</h2><strong>S/ {Number(selected.price).toFixed(2)}</strong>{selected.status!=='active'&&<span className={`publicationState ${selected.status}`}>{selected.status}</span>}</div></div><p className="marketDescription">{selected.description}</p><div className="modalFacts"><span><UserRound size={17}/><b>Vendedor</b>@{selected.seller_username} {selected.verified?'· Verificado':''}</span><span><MapPin size={17}/><b>Zona</b>{selected.zone} · {distanceLabel(selected.distance_km)}</span><span><Clock3 size={17}/><b>Publicado</b>{timeLabel(selected.created_at)}</span><span><PackageCheck size={17}/><b>Entrega</b>{selected.delivery?'Entrega coordinada':'Recojo en zona'}</span><span><Sparkles size={17}/><b>Actividad</b>{selected.views||0} vistas · {selected.contact_count||0} contactos</span></div><div className="safeNotice"><ShieldCheck size={20}/><div><b>Consejo de seguridad</b><span>Revisa el artículo antes de pagar y conserva la conversación dentro de MiZona.</span></div></div><div className="modalActions">{selected.is_mine?<><button className="secondary" onClick={()=>setStatus(selected.id,selected.status==='paused'?'active':'paused')}>{selected.status==='paused'?'Reactivar':'Pausar'}</button><button className="primary" onClick={()=>setStatus(selected.id,'sold')}>Marcar vendido</button></>:<><button className="secondary" onClick={()=>toggleLocalListingFavorite(selected.id)}><Heart size={17}/> Guardar</button><button className="secondary" onClick={()=>{reportLocalListing(selected.id,'Publicación sospechosa','Reporte desde el detalle');notify('Reporte enviado.');}}><Flag size={17}/> Reportar</button><button className="primary" onClick={()=>contactSeller(selected)}><MessageCircle size={17}/> Chatear con vendedor</button></>}</div></section></div>}

    {showPublish&&<div className="modalBackdrop" onMouseDown={()=>setShowPublish(false)}><section className="benefitCreateModal" onMouseDown={e=>e.stopPropagation()}><div className="benefitModalHead"><div><p className="eyebrow">Nueva publicación</p><h2>Publicar en Marketplace</h2></div><button onClick={()=>setShowPublish(false)}><X size={18}/></button></div><p className="muted">Los usuarios normales pasan por revisión. Las cuentas estudiantiles tienen categorías limitadas.</p><div className="benefitFormGrid"><label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ej. Bicicleta aro 20"/></label><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value,image:categoryEmoji[e.target.value]||'📦'})}>{categories.filter(x=>x.id!=='all').map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Precio<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Condición<select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}><option>Nuevo</option><option>Usado - excelente</option><option>Usado - bueno</option><option>Usado - regular</option><option>Servicio</option></select></label><label>Zona<input value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})}/></label><label>Foto local<input type="file" accept="image/*" onChange={chooseImage}/></label><label className="wide">Descripción<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe el estado, accesorios y forma de entrega"/></label><label className="commerceCheck"><input type="checkbox" checked={form.delivery} onChange={e=>setForm({...form,delivery:e.target.checked})}/> Ofrezco entrega coordinada</label><label className="commerceCheck"><input type="checkbox" checked={form.negotiable} onChange={e=>setForm({...form,negotiable:e.target.checked})}/> Precio negociable</label></div>{form.image_data&&<div className="commerceImagePreview"><img src={form.image_data} alt="Vista previa"/><button onClick={()=>setForm({...form,image_data:null})}>Quitar imagen</button></div>}<div className="benefitFormActions"><button className="secondary" onClick={()=>setShowPublish(false)}>Cancelar</button><button className="primary" onClick={publish}>Enviar publicación</button></div></section></div>}
    {toast&&<div className="toastSuccess"><Sparkles size={17}/>{toast}</div>}{error&&<div className="toastError">⚠️ {error}<button onClick={()=>setError('')}>×</button></div>}
  </div>;
}
