import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle, CreditCard, Download, FlaskConical, Receipt, RefreshCw, Settings, Settings2, ShieldCheck } from 'lucide-react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import { useApp } from '../context/AppContext';
import { createDemoPayment,downloadPaymentsReport,getPaymentsState,resetPayments,setDefaultPaymentModel,subscribePayments,updateDemoPayment,updatePaymentModel,updatePaymentSettings } from '../lib/localPayments';
import { isPlatformAdmin } from '../lib/permissions';
const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(n||0));
const labels={direct_seller:'Pago directo',cash_delivery:'Contra entrega',payment_link:'Enlace/QR',platform_checkout:'Checkout MiZona',protected_payment:'Pago protegido',split_payment:'Pago dividido'};
export default function Payments(){
 const {profile}=useApp(); const admin=isPlatformAdmin(profile); const [state,setState]=useState(getPaymentsState); const [tab,setTab]=useState(admin?'config':'methods'); const [msg,setMsg]=useState('');
 const models=Array.isArray(state?.models)?state.models:[]; const transactions=Array.isArray(state?.transactions)?state.transactions:[]; const settings=state?.settings||{}; const active=models.filter(m=>m.enabled&&m.public);
 const [form,setForm]=useState(()=>({buyer:profile.displayName,seller:'Negocio verificado',concept:'Compra de prueba',amount:100,model:settings.default_model||'direct_seller'}));
 useEffect(()=>subscribePayments(setState),[]);
 const summary=useMemo(()=>({total:transactions.reduce((a,t)=>a+Number(t.amount||0),0),held:transactions.filter(t=>t.status==='held').reduce((a,t)=>a+Number(t.amount||0),0),completed:transactions.filter(t=>t.status==='completed').length}),[state]);
 const saveSettings=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setState(updatePaymentSettings({platform_name:fd.get('platform_name'),commission_percent:Number(fd.get('commission_percent')),fixed_fee:Number(fd.get('fixed_fee')),minimum_amount:Number(fd.get('minimum_amount')),maximum_amount:Number(fd.get('maximum_amount')),hold_days:Number(fd.get('hold_days')),refund_window_days:Number(fd.get('refund_window_days')),provider:fd.get('provider'),bank_account_label:fd.get('bank_account_label'),bank_account_mask:fd.get('bank_account_mask'),wallet_phone:fd.get('wallet_phone'),require_verified_seller:fd.get('require_verified_seller')==='on'}));setMsg('Configuración guardada.');};
 const simulate=e=>{e.preventDefault();try{createDemoPayment(form);setMsg('Pago de prueba creado. No mueve dinero real.');}catch(err){setMsg(err.message)}};
 return <div className="page paymentsPage"><div className="hero compact"><div><span className="eyebrow">Etapa 22</span><h1>Pagos MiZona</h1><p>Todos los modelos de pago, activables y configurables por el administrador.</p></div><div className="heroIcon"><CreditCard/></div></div>
 <div className="paymentWarning"><AlertTriangle/><div><b>Simulación local</b><span>Esta etapa no cobra dinero real. Los modelos protegidos o divididos requieren una pasarela autorizada, contratos y revisión legal antes de activarse en producción.</span></div></div>
 <Tabs value={tab} onChange={setTab} items={[{id:'methods',label:'Métodos'},{id:'simulate',label:'Probar flujo'},{id:'history',label:'Movimientos'},...(admin?[{id:'config',label:'Administración'}]:[])]}/>
 {msg&&<p className="accountMessage">{msg}</p>}
 {tab==='methods'&&<><div className="paymentKpis"><span><b>{active.length}</b>Métodos públicos</span><span><b>{labels[settings.default_model]}</b>Predeterminado</span><span><b>{settings.commission_percent}%</b>Comisión base</span><span><b>{settings.require_verified_seller?'Sí':'No'}</b>Exige vendedor verificado</span></div><div className="paymentGrid">{models.filter(m=>m.public&&m.enabled).map(m=><Card key={m.id} title={m.name} icon={m.requires_provider?'💳':'🤝'}><p>{m.description}</p><div className="paymentMeta"><span>Comisión: <b>{m.commission_percent}%</b></span><span>Riesgo: <b>{m.risk}</b></span></div>{settings.default_model===m.id&&<em className="defaultPay">Método predeterminado</em>}</Card>)}</div><Card title="Protección para el cliente" icon={<ShieldCheck size={18}/>}><ul className="list"><li>El cliente ve quién recibe el dinero antes de confirmar.</li><li>Los pagos externos muestran advertencia y no se presentan como protegidos.</li><li>Pago protegido solo se habilita para vendedores verificados.</li><li>Todo cambio del administrador queda registrado localmente.</li></ul></Card></>}
 {tab==='simulate'&&<div className="grid2"><Card title="Crear pago de prueba" icon={<FlaskConical size={18}/>}><form className="paymentForm" onSubmit={simulate}><label>Comprador<input value={form.buyer} onChange={e=>setForm({...form,buyer:e.target.value})}/></label><label>Vendedor<input value={form.seller} onChange={e=>setForm({...form,seller:e.target.value})}/></label><label>Concepto<input value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})}/></label><label>Monto<input type="number" min="1" step="0.10" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Modelo<select value={form.model} onChange={e=>setForm({...form,model:e.target.value})}>{models.filter(m=>m.enabled).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button>Simular pago</button></form></Card><Card title="Flujo seleccionado" icon={<RefreshCw size={18}/>}><ol className="paymentFlow"><li>Cliente revisa monto y receptor.</li><li>MiZona registra el intento de pago.</li><li>{['protected_payment','platform_checkout','split_payment'].includes(form.model)?'El dinero queda marcado como retenido hasta confirmación.':'El pago se coordina según el método seleccionado.'}</li><li>Se confirma, libera, devuelve o cancela.</li></ol><p className="muted">No se conecta a bancos, Yape, Plin ni tarjetas en esta etapa.</p></Card></div>}
 {tab==='history'&&<><div className="paymentKpis"><span><b>{money(summary.total)}</b>Volumen simulado</span><span><b>{money(summary.held)}</b>Retenido</span><span><b>{summary.completed}</b>Completados</span><span><b>{transactions.length}</b>Operaciones</span></div><Card title="Movimientos locales" icon={<Receipt size={18}/>}><div className="paymentTable">{transactions.map(t=><article key={t.id}><div><b>{t.id} · {t.concept}</b><span>{t.buyer} → {t.seller} · {labels[t.model]||t.model}</span></div><strong>{money(t.amount)}</strong><em className={`payStatus ${t.status}`}>{t.status}</em>{admin&&<div className="payActions">{t.status!=='completed'&&<button onClick={()=>updateDemoPayment(t.id,'completed')}>Completar</button>}{t.status==='held'&&<button onClick={()=>updateDemoPayment(t.id,'refunded')}>Devolver</button>}{!['cancelled','refunded'].includes(t.status)&&<button className="dangerButton" onClick={()=>updateDemoPayment(t.id,'cancelled')}>Cancelar</button>}</div>}</article>)}</div></Card></>}
 {tab==='config'&&admin&&<><div className="grid2"><Card title="Configuración general" icon={<Settings size={18}/>}><form className="paymentForm" onSubmit={saveSettings}><label>Nombre de plataforma<input name="platform_name" defaultValue={settings.platform_name}/></label><label>Proveedor o pasarela<input name="provider" defaultValue={settings.provider}/></label><label>Comisión base (%)<input name="commission_percent" type="number" step="0.1" defaultValue={settings.commission_percent}/></label><label>Cargo fijo (S/)<input name="fixed_fee" type="number" step="0.1" defaultValue={settings.fixed_fee}/></label><label>Monto mínimo<input name="minimum_amount" type="number" defaultValue={settings.minimum_amount}/></label><label>Monto máximo<input name="maximum_amount" type="number" defaultValue={settings.maximum_amount}/></label><label>Días de retención<input name="hold_days" type="number" defaultValue={settings.hold_days}/></label><label>Días para devolución<input name="refund_window_days" type="number" defaultValue={settings.refund_window_days}/></label><label>Nombre de cuenta receptora<input name="bank_account_label" defaultValue={settings.bank_account_label}/></label><label>Cuenta enmascarada<input name="bank_account_mask" defaultValue={settings.bank_account_mask}/></label><label>Teléfono de billetera<input name="wallet_phone" defaultValue={settings.wallet_phone}/></label><label className="checkLabel"><input name="require_verified_seller" type="checkbox" defaultChecked={settings.require_verified_seller}/> Exigir vendedor verificado</label><button>Guardar configuración</button></form></Card><Card title="Controles administrativos" icon={<ShieldCheck size={18}/>}><div className="paymentAdminModels">{models.map(m=><article key={m.id}><div><b>{m.name}</b><span>{m.description}</span></div><label><input type="checkbox" checked={m.enabled} onChange={e=>setState(updatePaymentModel(m.id,{enabled:e.target.checked}))}/> Activo</label><label><input type="checkbox" checked={m.public} onChange={e=>setState(updatePaymentModel(m.id,{public:e.target.checked}))}/> Público</label><label>Comisión %<input type="number" step="0.1" value={m.commission_percent} onChange={e=>setState(updatePaymentModel(m.id,{commission_percent:Number(e.target.value)}))}/></label><button disabled={!m.enabled||settings.default_model===m.id} onClick={()=>{try{setState(setDefaultPaymentModel(m.id));setMsg('Método predeterminado actualizado.')}catch(err){setMsg(err.message)}}}>{settings.default_model===m.id?'Predeterminado':'Usar por defecto'}</button></article>)}</div></Card></div><div className="paymentFooterActions"><button onClick={downloadPaymentsReport}><Download size={16}/> Descargar configuración</button><button className="dangerButton" onClick={()=>{if(confirm('¿Restablecer todos los pagos simulados?')){setState(resetPayments());setMsg('Pagos restablecidos.')}}}><RefreshCw size={16}/> Restablecer</button></div></>}
 </div>;
}
