import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Download, FlaskConical, Rocket, ShieldCheck, Smartphone, Users } from 'lucide-react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import { addIncident, addPilotUser, createReleaseCandidate, exportQualityReport, getQualityState, runQualityTests, subscribeQuality, updateChecklist, updateIncident, updatePilotUser, updateQualitySettings } from '../lib/localQuality';

const statusLabel={pending:'Pendiente',doing:'En prueba',done:'Listo',blocked:'Bloqueado',open:'Abierta',investigating:'Investigando',closed:'Cerrada',planned:'Planificado',active:'Activo',finished:'Finalizado',ok:'Correcto',warning:'Advertencia',fail:'Falla',candidate:'Candidato',blocked_release:'Bloqueado'};
export default function QualityCenter(){
 const [state,setState]=useState(getQualityState); const [tab,setTab]=useState('dashboard'); const [msg,setMsg]=useState('');
 const [incident,setIncident]=useState({title:'',module:'General',severity:'medium',detail:''});
 const [pilot,setPilot]=useState({name:'',role:'Usuario piloto',group:'General'});
 useEffect(()=>subscribeQuality(setState),[]);
 const summary=useMemo(()=>({done:state.checklist.filter(x=>x.status==='done').length,critical:state.incidents.filter(x=>x.severity==='critical'&&x.status!=='closed').length,open:state.incidents.filter(x=>x.status!=='closed').length,testsOk:state.tests.filter(x=>x.status==='ok').length}),[state]);
 const run=async()=>{await runQualityTests();setMsg('Diagnóstico ejecutado. Revisa advertencias y fallas antes del piloto.');};
 return <div className="page qualityPage">
  <div className="hero compact"><div><span className="eyebrow">Etapa 27</span><h1>Calidad, seguridad y lanzamiento piloto</h1><p>Revisión final de módulos, perfiles, celular, respaldo, incidencias y candidatos de publicación.</p></div><div className="heroIcon"><ShieldCheck/></div></div>
  <div className="paymentWarning"><AlertTriangle/><div><b>Este centro no reemplaza una auditoría externa</b><span>Organiza las pruebas locales y evita publicar con fallas críticas. Pagos reales, identidad, GPS y datos personales requieren validación técnica y legal adicional.</span></div></div>
  <Tabs value={tab} onChange={setTab} items={[{id:'dashboard',label:'Estado'},{id:'checklist',label:'Checklist'},{id:'incidents',label:'Incidencias'},{id:'pilot',label:'Piloto'},{id:'release',label:'Publicación'},{id:'settings',label:'Reglas'}]}/>
  {msg&&<p className="accountMessage">{msg}</p>}
  {tab==='dashboard'&&<>
   <div className="paymentKpis"><span><b>{summary.done}/{state.checklist.length}</b>Controles listos</span><span><b>{summary.testsOk}/{state.tests.length||0}</b>Pruebas correctas</span><span><b>{summary.open}</b>Incidencias abiertas</span><span><b>{summary.critical}</b>Críticas activas</span></div>
   <div className="grid2">
    <Card title="Diagnóstico automático" icon={<FlaskConical/>}><p>Revisa almacenamiento, conexión, PWA, espacio, perfiles, pagos, protección estudiantil y archivos.</p><button onClick={run}><ClipboardCheck size={16}/> Ejecutar diagnóstico</button><div className="qualityTests">{state.tests.map(t=><article key={t.id}><div><b>{t.label}</b><span>{t.detail}</span></div><em className={`payStatus ${t.status}`}>{statusLabel[t.status]||t.status}</em></article>)}</div></Card>
    <Card title="Preparación del piloto" icon={<Rocket/>}><ul className="list"><li>Probar primero con datos simulados.</li><li>Usar un colegio, un comité y un negocio piloto.</li><li>No activar dinero real mientras falte backend seguro.</li><li>Guardar respaldo antes de cada publicación.</li><li>Registrar todo error con pantalla y pasos.</li></ul><button onClick={exportQualityReport}><Download size={16}/> Descargar reporte</button></Card>
   </div>
  </>}
  {tab==='checklist'&&<Card title="Lista de control integral" icon={<CheckCircle2/>}><div className="qualityChecklist">{state.checklist.map(item=><article key={item.id}><div><b>{item.label}</b><span>{item.detail}</span><input className="field" placeholder="Observación" value={item.note||''} onChange={e=>updateChecklist(item.id,{note:e.target.value})}/></div><select value={item.status} onChange={e=>updateChecklist(item.id,{status:e.target.value})}><option value="pending">Pendiente</option><option value="doing">En prueba</option><option value="done">Listo</option><option value="blocked">Bloqueado</option></select></article>)}</div></Card>}
  {tab==='incidents'&&<div className="grid2">
   <Card title="Registrar incidencia" icon={<AlertTriangle/>}><form className="paymentForm" onSubmit={e=>{e.preventDefault();addIncident(incident);setIncident({title:'',module:'General',severity:'medium',detail:''});setMsg('Incidencia registrada.');}}><label>Título<input required value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})}/></label><label>Módulo<input value={incident.module} onChange={e=>setIncident({...incident,module:e.target.value})}/></label><label>Severidad<select value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><label>Detalle<textarea value={incident.detail} onChange={e=>setIncident({...incident,detail:e.target.value})}/></label><button>Guardar incidencia</button></form></Card>
   <Card title="Incidencias registradas" icon="🧯"><div className="qualityIncidents">{state.incidents.length?state.incidents.map(item=><article key={item.id}><div><b>{item.id} · {item.title}</b><span>{item.module} · {item.severity}</span><small>{item.detail}</small></div><select value={item.status} onChange={e=>updateIncident(item.id,{status:e.target.value})}><option value="open">Abierta</option><option value="investigating">Investigando</option><option value="closed">Cerrada</option></select></article>):<p className="muted">No hay incidencias registradas.</p>}</div></Card>
  </div>}
  {tab==='pilot'&&<>
   <div className="grid2"><Card title="Agregar participante" icon={<Users/>}><form className="paymentForm" onSubmit={e=>{e.preventDefault();addPilotUser(pilot);setPilot({name:'',role:'Usuario piloto',group:'General'});}}><label>Nombre<input required value={pilot.name} onChange={e=>setPilot({...pilot,name:e.target.value})}/></label><label>Rol<input value={pilot.role} onChange={e=>setPilot({...pilot,role:e.target.value})}/></label><label>Grupo<select value={pilot.group} onChange={e=>setPilot({...pilot,group:e.target.value})}><option>General</option><option>Colegio</option><option>Comité</option><option>Negocio</option><option>Conductor</option></select></label><button>Agregar al piloto</button></form></Card><Card title="Prueba móvil obligatoria" icon={<Smartphone/>}><ul className="list"><li>Android pequeño: 360–390 px.</li><li>Android grande: 412–480 px.</li><li>Tablet vertical y horizontal.</li><li>PC con zoom 100 % y 125 %.</li><li>Abrir y cerrar menú 20 veces.</li><li>Probar teclado, formularios y tablas largas.</li></ul></Card></div>
   <Card title="Participantes del piloto" icon="🧪"><div className="qualityPilot">{state.pilotUsers.map(item=><article key={item.id}><div><b>{item.name}</b><span>{item.role} · {item.group}</span></div><select value={item.status} onChange={e=>updatePilotUser(item.id,{status:e.target.value})}><option value="planned">Planificado</option><option value="active">Activo</option><option value="finished">Finalizado</option></select></article>)}</div></Card>
  </>}
  {tab==='release'&&<>
   <Card title="Candidato de publicación" icon={<Rocket/>}><p>Genera una fotografía del estado actual. Se bloqueará cuando existan pruebas fallidas o incidencias críticas abiertas.</p><button onClick={()=>{const next=createReleaseCandidate();const r=next.releases[0];setMsg(r.status==='blocked'?'Publicación bloqueada: corrige fallas críticas.':'Candidato creado para revisión final.');}}>Crear candidato</button></Card>
   <Card title="Historial de candidatos" icon="📦"><div className="qualityReleases">{state.releases.length?state.releases.map(r=><article key={r.id}><div><b>{r.id}</b><span>{new Date(r.createdAt).toLocaleString()} · checklist {r.checklistDone}/{r.totalChecklist}</span></div><em className={`payStatus ${r.status==='blocked'?'fail':'ok'}`}>{r.status==='blocked'?'Bloqueado':'Candidato'}</em></article>):<p className="muted">Todavía no se ha creado ningún candidato.</p>}</div></Card>
  </>}
  {tab==='settings'&&<Card title="Reglas de calidad" icon="⚙️"><form className="paymentForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);updateQualitySettings({pilotName:f.get('pilotName'),environment:f.get('environment'),releaseChannel:f.get('releaseChannel'),blockReleaseOnCritical:f.get('blockReleaseOnCritical')==='on',requireBackup:f.get('requireBackup')==='on',requireStudentTest:f.get('requireStudentTest')==='on'});setMsg('Reglas guardadas.');}}><label>Nombre del piloto<input name="pilotName" defaultValue={state.settings.pilotName}/></label><label>Entorno<select name="environment" defaultValue={state.settings.environment}><option value="local">Local</option><option value="staging">Pruebas en nube</option><option value="production">Producción</option></select></label><label>Canal<select name="releaseChannel" defaultValue={state.settings.releaseChannel}><option value="interno">Interno</option><option value="piloto">Piloto cerrado</option><option value="publico">Público</option></select></label><label className="checkLabel"><input name="blockReleaseOnCritical" type="checkbox" defaultChecked={state.settings.blockReleaseOnCritical}/> Bloquear publicación con incidencias críticas</label><label className="checkLabel"><input name="requireBackup" type="checkbox" defaultChecked={state.settings.requireBackup}/> Exigir respaldo antes de publicar</label><label className="checkLabel"><input name="requireStudentTest" type="checkbox" defaultChecked={state.settings.requireStudentTest}/> Exigir prueba con perfil estudiantil</label><button>Guardar reglas</button></form></Card>}
 </div>;
}
