import {useEffect,useMemo,useState} from 'react';
import {ShieldCheck,AlertTriangle,FileCheck2,Download,Search,Flag} from 'lucide-react';
import Card from '../components/Card';
import Tabs from '../components/Tabs';
import {useApp} from '../context/AppContext';
import {addReport,createVerificationRequest,downloadVerificationReport,getVerificationState,subscribeVerification,toggleCheck,updateReport,updateRequest,updateVerificationSettings} from '../lib/localVerification';
import {isPlatformAdmin} from '../lib/permissions';
const statusLabel={pending:'Pendiente',observed:'Observado',approved:'Aprobado',expired:'Vencido',suspended:'Suspendido',rejected:'Rechazado'};
const checks={identity:'Identidad',phone:'Teléfono',ruc:'RUC',address:'Local/dirección',license:'Licencia',professional:'Acreditación profesional'};
export default function Verification(){
 const {profile}=useApp();const admin=isPlatformAdmin(profile);const [state,setState]=useState(getVerificationState);const [tab,setTab]=useState(admin?'review':'public');const [msg,setMsg]=useState('');const [q,setQ]=useState('');
 useEffect(()=>subscribeVerification(setState),[]);
 const visible=useMemo(()=>state.requests.filter(r=>`${r.business} ${r.ruc} ${r.legalName}`.toLowerCase().includes(q.toLowerCase())),[state,q]);
 const submit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);createVerificationRequest({ownerId:profile.id,business:f.get('business'),type:f.get('type'),ruc:f.get('ruc'),legalName:f.get('legalName'),activity:f.get('activity'),address:f.get('address'),expiresAt:f.get('expiresAt'),documents:[...e.currentTarget.querySelectorAll('input[type=file]')].flatMap(x=>[...x.files].map(file=>({name:file.name,type:x.dataset.type||'Documento'})))});e.currentTarget.reset();setMsg('Solicitud registrada para revisión.');};
 return <div className="page"><div className="hero compact"><div><span className="eyebrow">Etapa 23</span><h1>Verificación y Antifraude</h1><p>Identidad, RUC, licencias, reputación, reportes y suspensión preventiva.</p></div><div className="heroIcon"><ShieldCheck/></div></div>
 <div className="paymentWarning"><AlertTriangle/><div><b>Verificación responsable</b><span>Un distintivo confirma documentos revisados, pero no garantiza el comportamiento futuro. Evita pagos fuera de MiZona y reporta cualquier irregularidad.</span></div></div>
 <Tabs value={tab} onChange={setTab} items={[{id:'public',label:'Empresas verificadas'},{id:'request',label:'Solicitar verificación'},{id:'reports',label:'Reportes'},...(admin?[{id:'review',label:'Revisión administrativa'},{id:'settings',label:'Configuración'}]:[])]}/>{msg&&<p className="accountMessage">{msg}</p>}
 {tab==='public'&&<><div className="toolbar"><Search size={18}/><input placeholder="Buscar empresa, RUC o razón social" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="grid2">{visible.map(r=><Card key={r.id} title={r.business} icon={r.status==='approved'?'✅':'🕒'}><p><b>{r.legalName||'Sin razón social'}</b><br/>{r.activity} · RUC {r.ruc||'no registrado'}</p><p><span className={`payStatus ${r.status}`}>{statusLabel[r.status]}</span> Riesgo local: <b>{r.risk}/100</b></p><div className="verificationBadges">{Object.entries(r.checks).filter(([,v])=>v).map(([k])=><span key={k}>✓ {checks[k]}</span>)}</div><small>Vigencia: {r.expiresAt||'Sin fecha'}</small><button className="dangerButton" onClick={()=>{addReport({targetId:r.id,reporter:profile.displayName,reason:'Reporte enviado desde la ficha'});setMsg('Reporte enviado para revisión.')}}><Flag size={14}/> Reportar</button></Card>)}</div></>}
 {tab==='request'&&<Card title="Nueva solicitud" icon="📄"><form className="paymentForm" onSubmit={submit}><label>Nombre comercial<input name="business" required/></label><label>Tipo<select name="type"><option value="business">Empresa o negocio</option><option value="service">Prestador de servicio</option><option value="professional">Profesional</option></select></label><label>RUC<input name="ruc" maxLength="11"/></label><label>Razón social o nombre legal<input name="legalName"/></label><label>Actividad<input name="activity" required/></label><label>Dirección<input name="address"/></label><label>Vencimiento principal<input name="expiresAt" type="date"/></label><label>DNI responsable<input type="file" data-type="Identidad"/></label><label>Ficha RUC<input type="file" data-type="RUC"/></label><label>Licencia o certificado<input type="file" data-type="Licencia/Certificado"/></label><button>Enviar solicitud</button></form></Card>}
 {tab==='reports'&&<Card title="Reportes registrados" icon="🚩"><div className="paymentTable">{state.reports.map(r=><article key={r.id}><div><b>{r.id} · {r.reason}</b><span>Objetivo: {r.targetId} · Reportado por {r.reporter}</span></div><em className={`payStatus ${r.status}`}>{r.status}</em>{admin&&<div className="payActions"><button onClick={()=>updateReport(r.id,'resolved')}>Resolver</button><button className="dangerButton" onClick={()=>updateReport(r.id,'dismissed')}>Descartar</button></div>}</article>)}</div></Card>}
 {tab==='review'&&admin&&<><div className="paymentKpis"><span><b>{state.requests.filter(x=>x.status==='pending').length}</b>Pendientes</span><span><b>{state.requests.filter(x=>x.status==='approved').length}</b>Aprobadas</span><span><b>{state.requests.filter(x=>x.status==='suspended').length}</b>Suspendidas</span><span><b>{state.reports.filter(x=>x.status==='open').length}</b>Reportes abiertos</span></div>{state.requests.map(r=><Card key={r.id} title={`${r.id} · ${r.business}`} icon={<FileCheck2/>}><p>{r.legalName} · RUC {r.ruc||'—'} · {r.address}</p><div className="verificationChecks">{Object.entries(checks).map(([k,l])=><label key={k}><input type="checkbox" checked={!!r.checks[k]} onChange={e=>toggleCheck(r.id,k,e.target.checked)}/> {l}</label>)}</div><p>Documentos: {(r.documents||[]).map(d=>d.name).join(', ')||'Sin archivos'}</p><div className="payActions"><button onClick={()=>updateRequest(r.id,{status:'approved',notes:'Documentos aprobados.'},profile.displayName)}>Aprobar</button><button onClick={()=>updateRequest(r.id,{status:'observed',notes:'Requiere corrección.'},profile.displayName)}>Observar</button><button className="dangerButton" onClick={()=>updateRequest(r.id,{status:'suspended'},profile.displayName)}>Suspender</button><button className="dangerButton" onClick={()=>updateRequest(r.id,{status:'rejected'},profile.displayName)}>Rechazar</button></div></Card>)}</>}
 {tab==='settings'&&admin&&<Card title="Reglas antifraude" icon="⚙️"><form className="paymentForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);updateVerificationSettings({requireVerifiedForProtectedPayments:f.get('required')==='on',autoSuspendReports:Number(f.get('reports')),reviewDays:Number(f.get('days')),showPublicDetails:f.get('public')==='on'});setMsg('Reglas actualizadas.')}}><label className="checkLabel"><input name="required" type="checkbox" defaultChecked={state.settings.requireVerifiedForProtectedPayments}/> Exigir verificación para pago protegido</label><label>Reportes para suspensión preventiva<input name="reports" type="number" min="1" defaultValue={state.settings.autoSuspendReports}/></label><label>Días objetivo de revisión<input name="days" type="number" min="1" defaultValue={state.settings.reviewDays}/></label><label className="checkLabel"><input name="public" type="checkbox" defaultChecked={state.settings.showPublicDetails}/> Mostrar detalle público de verificaciones</label><button>Guardar reglas</button></form><button onClick={downloadVerificationReport}><Download size={16}/> Descargar reporte JSON</button></Card>}
 </div>;
}
