-- MiZona Enterprise V8 30.70
create table if not exists public.app_sync_events (
  id bigint generated by default as identity primary key,
  client_event_id text not null unique,
  user_id uuid null references auth.users(id) on delete set null,
  local_actor_id text null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  payload jsonb not null default '{}'::jsonb,
  device_id text null,
  client_created_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists app_sync_events_user_created_idx on public.app_sync_events(user_id, created_at desc);
create index if not exists app_sync_events_entity_idx on public.app_sync_events(entity_type, entity_id, created_at desc);
alter table public.app_sync_events enable row level security;
drop policy if exists "app_sync_events_select_own" on public.app_sync_events;
create policy "app_sync_events_select_own" on public.app_sync_events for select to authenticated using (user_id = auth.uid());
drop policy if exists "app_sync_events_insert_own" on public.app_sync_events;
create policy "app_sync_events_insert_own" on public.app_sync_events for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "app_sync_events_update_own" on public.app_sync_events;
create policy "app_sync_events_update_own" on public.app_sync_events for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
