-- MiZona 30.73: operaciones normalizadas de Business
create table if not exists public.mz_business_workers (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  local_user_id text null,
  role text not null check (role in ('owner','manager','cashier','cook','waiter')),
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_customers (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  name text not null,
  phone text default '',
  email text default '',
  visits integer not null default 0,
  total_spent numeric(12,2) not null default 0,
  points integer not null default 0,
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_cash_sessions (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  local_user_id text null,
  opening_amount numeric(12,2) not null default 0,
  counted_amount numeric(12,2),
  expected_amount numeric(12,2),
  difference numeric(12,2),
  status text not null default 'open' check (status in ('open','closed')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_sales (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  order_id text null,
  customer_id text null references public.mz_business_customers(id) on delete set null,
  cash_session_id text null references public.mz_cash_sessions(id) on delete set null,
  cashier_user_id uuid null references auth.users(id) on delete set null,
  local_cashier_id text null,
  receipt text not null,
  payment_method text not null default 'cash',
  subtotal numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  cash_received numeric(12,2) not null default 0,
  change_amount numeric(12,2) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_business_sale_items (
  id bigint generated by default as identity primary key,
  sale_id text not null references public.mz_business_sales(id) on delete cascade,
  product_id text null references public.mz_products(id) on delete set null,
  name text not null,
  quantity numeric(12,3) not null default 1,
  unit_price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.mz_business_expenses (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  cash_session_id text null references public.mz_cash_sessions(id) on delete set null,
  created_by uuid null references auth.users(id) on delete set null,
  local_created_by text null,
  category text not null default 'Otros',
  description text default '',
  amount numeric(12,2) not null check (amount >= 0),
  payment_method text not null default 'cash',
  receipt_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mz_inventory_movements (
  id text primary key,
  business_id text not null references public.mz_businesses(id) on delete cascade,
  product_id text not null references public.mz_products(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  local_user_id text null,
  quantity numeric(12,3) not null,
  reason text default '',
  reference_type text default 'manual',
  reference_id text null,
  created_at timestamptz not null default now()
);

create index if not exists mz_workers_business_idx on public.mz_business_workers(business_id);
create index if not exists mz_customers_business_idx on public.mz_business_customers(business_id);
create index if not exists mz_cash_business_idx on public.mz_cash_sessions(business_id, status);
create index if not exists mz_sales_business_idx on public.mz_business_sales(business_id, created_at desc);
create index if not exists mz_expenses_business_idx on public.mz_business_expenses(business_id, created_at desc);
create index if not exists mz_inventory_business_idx on public.mz_inventory_movements(business_id, created_at desc);

alter table public.mz_business_workers enable row level security;
alter table public.mz_business_customers enable row level security;
alter table public.mz_cash_sessions enable row level security;
alter table public.mz_business_sales enable row level security;
alter table public.mz_business_sale_items enable row level security;
alter table public.mz_business_expenses enable row level security;
alter table public.mz_inventory_movements enable row level security;

create or replace function public.mz_can_manage_business(target_business text)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.mz_businesses b
    where b.id=target_business and b.owner_user_id=auth.uid()
  ) or exists(
    select 1 from public.mz_business_members m
    where m.business_id=target_business and m.user_id=auth.uid() and m.status='active'
  ) or exists(
    select 1 from public.mz_business_workers w
    where w.business_id=target_business and w.user_id=auth.uid() and w.status='active'
  );
$$;

do $$ begin
  create policy "business workers read" on public.mz_business_workers for select using (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "business workers write" on public.mz_business_workers for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "business customers access" on public.mz_business_customers for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "cash sessions access" on public.mz_cash_sessions for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "business sales access" on public.mz_business_sales for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "sale items access" on public.mz_business_sale_items for all using (
    exists(select 1 from public.mz_business_sales s where s.id=sale_id and public.mz_can_manage_business(s.business_id))
  ) with check (
    exists(select 1 from public.mz_business_sales s where s.id=sale_id and public.mz_can_manage_business(s.business_id))
  );
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "business expenses access" on public.mz_business_expenses for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "inventory movements access" on public.mz_inventory_movements for all using (public.mz_can_manage_business(business_id)) with check (public.mz_can_manage_business(business_id));
exception when duplicate_object then null; end $$;

alter publication supabase_realtime add table public.mz_business_workers;
alter publication supabase_realtime add table public.mz_business_customers;
alter publication supabase_realtime add table public.mz_cash_sessions;
alter publication supabase_realtime add table public.mz_business_sales;
alter publication supabase_realtime add table public.mz_business_expenses;
alter publication supabase_realtime add table public.mz_inventory_movements;
